### ISSUE TITLE
[Bug]: cant create new page on app from existing database table

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#12185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we are using perconas encrypted db with SCRAM-SHA-1

```
backend stdout |  - Going to fetch template application
backend stdout |
backend stdout |  - Mapping column names with template application for table va
backend stdout |
backend stdout |  - Going to update layout for page 623b7217b7b3113fe4705376 and layout 623b7217b7b3113fe4705374
backend stdout |
backend stdout |  - Going to clone actions from template application for page 623b7217b7b3113fe4705376
backend stdout |  - Cloning actions from template application for pageId 623b7217b7b3113fe4705376
backend stdout |
backend stdout |  - Cloning plugin specified templates for action
backend stdout |  - Cloning form data for action
backend stdout |
backend stdout |  -
backend stdout | java.lang.UnsupportedOperationException: not supported
backend stdout |        at java.base/java.util.KeyValueHolder.setValue(KeyValueHolder.java:91)
backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout |        *__checkpoint ⇢ Handler com.appsmith.server.controllers.PageController#createCRUDPage(String, CRUDPageResourceDTO, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout |                at java.base/java.util.KeyValueHolder.setValue(KeyValueHolder.java:91)
backend stdout |                at com.appsmith.server.solutions.ce.CreateDBTablePageSolutionCEImpl.updateFormData(CreateDBTablePageSolutionCEImpl.java:607)
backend stdout |                at com.appsmith.server.solutions.ce.CreateDBTablePageSolutionCEImpl.updateFormData(CreateDBTablePageSolutionCEImpl.java:619)
backend stdout |                at com.appsmith.server.solutions.ce.CreateDBTablePageSolutionCEImpl.updateFormData(CreateDBTablePageSolutionCEImpl.java:619)
backend stdout |                at com.appsmith.server.solutions.ce.CreateDBTablePageSolutionCEImpl.lambda$cloneActionsFromTemplateApplication$19(CreateDBTablePageSolutionCEImpl.java:578)
backend stdout |                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
backend stdout |                at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
backend stdout |                at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
backend stdout |                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
backend stdout |                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
backend stdout |                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
backend stdout |                at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
backend stdout |                at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
backend stdout |                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
backend stdout |                at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:325)
backend stdout |                at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232)
backend stdout |                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
backend stdout |                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
backend stdout |                at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
backend stdout |                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
backend stdout |                at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:268)
backend stdout |                at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527)
backend stdout |                at reactor.core.publisher.Operators.complete(Operators.java:137)
backend stdout |                at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
backend stdout |                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
backend stdout |                at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
backend stdout |                at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:439)
backend stdout |                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:784)
backend stdout |                at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:732)
backend stdout |                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:240)
backend stdout |                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:206)
backend stdout |                at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:197)
backend stdout |                at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:98)
backend stdout |                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
backend stdout |                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout |                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
backend stdout |                at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout |                at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout |                at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:207)
backend stdout |                at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:146)
backend stdout |                at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
backend stdout |                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4232)
backend stdout |                at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:104)
backend stdout |                at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:56)
backend stdout |                at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
backend stdout |                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout |                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout |                at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout |                at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout |                at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:73)
backend stdout |                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout |                at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:755)
backend stdout |                at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
backend stdout |                at com.mongodb.internal.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:483)
backend stdout |                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout |                at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:286)
backend stdout |                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout |                at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:84)
backend stdout |                at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:530)
backend stdout |                at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:142)
backend stdout |                at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:439)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:744)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:711)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout |                at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout |                at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout |                at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:350)
backend stdout |                at com.mongodb.connection.netty.NettyStream.access$1200(NettyStream.java:104)
backend stdout |                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:409)
backend stdout |                at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:406)
backend stdout |                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
backend stdout |                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout |                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout |                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout |                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
backend stdout |                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
backend stdout |                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
backend stdout |                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
backend stdout |                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
backend stdout |                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout |                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout |                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout |                at java.base/java.lang.Thread.run(Thread.java:829)

```

### Steps To Reproduce

1. new application
2. select datasource, collection
3. Select a searchable field from the selected collection
4. error on "generate page"

### Version

self hosted/ release branch

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer please tell us which db you are seeing this on and can you reproduce this on our cloud environment?

**Comment by japrogramer** [comment]
@Nikhil-Nandagopal  This happens when using [perconas ](https://www.percona.com/software/mongodb/percona-server-for-mongodb) on my local build of release branch.
I don't have access to the cloud environment.

im building on arch linux with jre, mvn clean compile and then ./build.sh

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer can you see if this is happening with the movies sample db that we ship with?
