### ISSUE TITLE
[Bug]: Timeout when git ssh url has a different domain than the https url

### ISSUE THREAD

**Issue by jgrgt** [appsmithorg/appsmith#12721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Setting up git sync fails when the SSH port of the git server is exposed on a different domain than the HTTPS port.

### Steps To Reproduce

Requirement: a git server that has an SSH port on domainA and an HTTPS port on domainB

When trying to set up git sync, enter the SSH url. Try to proceed, but the form will hang. In the backend you will find a timeout:

```
  - Process: JGIT status, Time elapsed: 729ms
  - boundedElastic-9: Switching to the branch master
  - Going to commit application 623d9c7ae50aa1038d108e57, branch : master
  - Error while checking if the repo is private:
 java.net.ConnectException: Connection timed out (Connection timed out)
     at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
     at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
     at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
     at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
     at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
     at java.base/java.net.Socket.connect(Socket.java:609)
     at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
     at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
     at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
     at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
     at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
     at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
     at com.appsmith.server.helpers.GitUtils.isRepoPrivate(GitUtils.java:63)
     at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$getApplicationCountWithPrivateRepo$208(GitServiceCEImpl.java:2288)
```

In the code, I found this snippet that makes an incorrect assumption that the SSH and HTTPS port are on the same domain:
```
    public static String convertSshUrlToBrowserSupportedUrl(String sshUrl) {
        if (StringUtils.isEmptyOrNull(sshUrl)) {
            throw new AppsmithException(AppsmithError.INVALID_PARAMETER, "ssh url");
        }
        return sshUrl
                .replaceFirst(".*git@", "https://")
                .replaceFirst("(\\.[a-z]*):", "$1/")
                .replaceFirst("\\.git$", "");
    }
```

Also:

1. `GitUtils.isRepoPrivate` uses blocking IO for this call, which seems highly undesirable in a WebFlux system?
2. It would be a good idea to set a connection timeout, because in firewalled environments, there's a good chance HTTPS is blocked off without refusing the connection, which might still cause a timeout...

### Version

1.6.18

**Comment by jgrgt** [comment]
Might be related to https://github.com/appsmithorg/appsmith/issues/12407#issuecomment-1092640915

**Comment by abhvsn** [comment]
@jgrgt thanks for the detailed report, and for taking this to next level by pointing out the root cause ❤️
