### ISSUE TITLE
[Bug]: Error when creating a new branch

### ISSUE THREAD

**Issue by leeahoward** [appsmithorg/appsmith#15195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I attempt to create a new branch I get a server error message and I receive the following error message in the appsmith logs. 

```
appsmith              | backend stdout |  - boundedElastic-4: Creating branch  ababafor the repo 621665bab2fb1d26e65b4383/62b47cd31007453d6057c145/appsmith3
appsmith              | backend stdout |
appsmith              | backend stdout |  - Execute time: JGIT git_create_branch, appId 62b47cd31007453d6057c145, Time elapsed: 294ms
appsmith              | backend stdout |
appsmith              | backend stdout |  -
appsmith              | backend stdout | java.lang.NullPointerException: null
appsmith              | backend stdout |        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeMapInternal(MappingMongoConverter.java:868)
appsmith              | backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
appsmith              | backend stdout | Error has been observed at the following site(s):
appsmith              | backend stdout |        *__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#createBranch(String, String, GitBranchDTO) [DispatcherHandler]
appsmith              | backend stdout | Original Stack Trace:
appsmith              | backend stdout |                at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeMapInternal(MappingMongoConverter.java:868)....
```

The branch appears to have been created, but when I try to switch to the branch I get another server error.

```
appsmith              | editor stdout |
appsmith              | backend stdout |  -
appsmith              | backend stdout | java.lang.NullPointerException: null
appsmith              | backend stdout |        at com.appsmith.server.services.ce.NewPageServiceCEImpl.lambda$findApplicationPagesByApplicationIdViewMode$12(NewPageServiceCEImpl.java:263)
appsmith              | backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
appsmith              | backend stdout | Error has been observed at the following site(s):
appsmith              | backend stdout |        *__checkpoint ⇢ Handler com.appsmith.server.controllers.PageController#getAllPages(String, String, ApplicationMode, String) [DispatcherHandler]
appsmith              | backend stdout | Original Stack Trace:
appsmith              | backend stdout |                at com.appsmith.server.services.ce.NewPageServiceCEImpl.lambda$findApplicationPagesByApplicationIdViewMode$12(NewPageServiceCEImpl.java:263)
appsmith              | backend stdout |                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)

```

I expect the branch to be created without error, and when switching to the branch I expect it to switch and function without error. 

### Steps To Reproduce

This happens when I enter the new branch name in the UI and then click create branch. 

### Version

self hosted 1.7.5 and 1.7.6

**Comment by Nikhil-Nandagopal** [comment]
@leeahoward are you still facing this issue? Could you try reproducing this on our cloud environment and share the sample app so we can debug it?

**Comment by leeahoward** [comment]
@Nikhil-Nandagopal I tried to reproduce it on the cloud environment and it worked as expected.  I also went back to my local app and created a branch and it worked as expected there. I am not sure what changed, but it seems to have fixed itself for the moment. 
Thanks

**Comment by Nikhil-Nandagopal** [comment]
@leeahoward That's good to hear. Do reach out if this happens again!
