### ISSUE TITLE
[Feature]: Redis IPv6 support [APPSMITH_REDIS_URL]

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#15209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently Appsmith does not support IPv6 redis hosts specified by the env var `APPSMITH_REDIS_URL`

### Logs when `APPSMITH_REDIS_URL=[0000:0000:0000:0000:0000:0000:0000:0001]:6379`

```Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [0000:0000:0000:0000:0000:0000:0000:0001]:6379
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
appsmith-watch-tower-testing | backend stdout | 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
appsmith-watch-tower-testing | backend stdout | 	... 44 common frames omitted
appsmith-watch-tower-testing | backend stdout | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /0:0:0:0:0:0:0:1:6379
appsmith-watch-tower-testing | backend stdout | Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Socket.connect(Socket.java:312)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-watch-tower-testing | backend stdout | 	at java.base/java.lang.Thread.run(Thread.java:829)Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [0000:0000:0000:0000:0000:0000:0000:0001]:6379
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330)
appsmith-watch-tower-testing | backend stdout | 	at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
appsmith-watch-tower-testing | backend stdout | 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
appsmith-watch-tower-testing | backend stdout | 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
appsmith-watch-tower-testing | backend stdout | 	... 44 common frames omitted
appsmith-watch-tower-testing | backend stdout | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /0:0:0:0:0:0:0:1:6379
appsmith-watch-tower-testing | backend stdout | Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.unix.Socket.connect(Socket.java:312)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
appsmith-watch-tower-testing | backend stdout | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
appsmith-watch-tower-testing | backend stdout | 	at java.base/java.lang.Thread.run(Thread.java:829)```

### Why should this be worked on?

Support for ipv6 redis

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal From the configuration property given in the original issue, this is for deployments. This should be a change in the Appsmith server code base. We need to look at the Redis library that we are using internally to connect to Redis for sessions.

**Comment by sharat87** [comment]
This isn't a DevOps issue. This has to do with how the backend server codebase interacts with Redis. Currently that interaction can only run with IPv4. If try to use a Redis with IPv6, the backend server fails to connect with Redis. We need to look into why the Redis driver we are using doesn't work with IPv6, and what we can do about it.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 so who should own this issue?

**Comment by sharat87** [comment]
@Nikhil-Nandagopal, I'm not sure which pod can take this up, but it needs a backend engineer's time. So BE pod perhaps?

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @ajinkyakulkarni can one of you help with who can pick this up?
