### ISSUE TITLE
[Bug]: Unable to update from v1.7.2

### ISSUE THREAD

**Issue by micael-pn** [appsmithorg/appsmith#15312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,
I tried to upgrade my appsmith instance from v1.7.2 to the latest version 1.7.8 but I faced an issue related to database migration

```
- method[migrateOrganizationIdToWorkspaceIdInDomainObjects] with arguments: [com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate, com.sun.proxy.$Proxy186]
 - FAILED OVER - ChangeEntry{, "id"="migrate-organizationId-to-workspaceId-in-domain-objects", "author"="", "class"="DatabaseChangelog2", "method"="migrateOrganizationIdToWorkspaceIdInDomainObjects"}
 - Mongock releasing the lock
 - Mongock released the lock
 - Mongock has finished
 - Error in mongock process. ABORTED MIGRATION
com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects] : Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockInitializingBeanRunner.afterPropertiesSet(MongockSpring5.java:84)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:447)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:194)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
	... 37 common frames omitted
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:131)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2899)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:555)
	at org.springframework.data.mongodb.core.MongoTemplate.doUpdate(MongoTemplate.java:1629)
	at org.springframework.data.mongodb.core.MongoTemplate.updateMulti(MongoTemplate.java:1583)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.lambda$updateMulti$102(MongockTemplate.java:658)
	at com.github.cloudyrock.mongock.driver.api.lock.guard.invoker.LockGuardInvokerImpl.invoke(LockGuardInvokerImpl.java:18)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.updateMulti(MongockTemplate.java:658)
	at com.appsmith.server.migrations.DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects(DatabaseChangelog2.java:953)
	... 45 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:279)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:253)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:431)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:251)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:76)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:194)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.OperationHelper.withReleasableConnection(OperationHelper.java:621)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:76)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:187)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1009)
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1000)
	at com.mongodb.client.internal.MongoCollectionImpl.updateMany(MongoCollectionImpl.java:646)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doUpdate$19(MongoTemplate.java:1638)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:553)
	... 51 common frames omitted
 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects] : Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
 - Closed connection [connectionId{localValue:5, serverValue:153829}] to 10.0.10.31:27017 because the pool has been closed.
 - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: Disconnected
Caused by: java.util.concurrent.CancellationException: Disconnected
	at reactor.core.publisher.FluxPublish$PublishSubscriber.disconnectAction(FluxPublish.java:314)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.dispose(FluxPublish.java:305)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription$State.terminate(LettuceReactiveSubscription.java:288)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription.lambda$cancel$6(LettuceReactiveSubscription.java:177)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onComplete(RedisPublisher.java:896)
	at io.lettuce.core.RedisPublisher$State.onAllDataRead(RedisPublisher.java:698)
	at io.lettuce.core.RedisPublisher$State$3.read(RedisPublisher.java:608)
	at io.lettuce.core.RedisPublisher$State$3.onDataAvailable(RedisPublisher.java:565)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onDataAvailable(RedisPublisher.java:326)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onAllDataRead(RedisPublisher.java:341)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:778)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.pubsub.PubSubCommandHandler.completeCommand(PubSubCommandHandler.java:260)
	at io.lettuce.core.pubsub.PubSubCommandHandler.notifyPushListeners(PubSubCommandHandler.java:220)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:646)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
 - 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects] : Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:447)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects] : Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockInitializingBeanRunner.afterPropertiesSet(MongockSpring5.java:84)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 23 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:194)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
	... 37 common frames omitted
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}; nested exception is com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:131)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2899)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:555)
	at org.springframework.data.mongodb.core.MongoTemplate.doUpdate(MongoTemplate.java:1629)
	at org.springframework.data.mongodb.core.MongoTemplate.updateMulti(MongoTemplate.java:1583)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.lambda$updateMulti$102(MongockTemplate.java:658)
	at com.github.cloudyrock.mongock.driver.api.lock.guard.invoker.LockGuardInvokerImpl.invoke(LockGuardInvokerImpl.java:18)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.updateMulti(MongockTemplate.java:658)
	at com.appsmith.server.migrations.DatabaseChangelog2.migrateOrganizationIdToWorkspaceIdInDomainObjects(DatabaseChangelog2.java:953)
	... 45 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'' on server 10.0.10.31:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", "code": 14, "codeName": "TypeMismatch"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:279)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:253)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:431)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:251)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:76)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:194)
	at com.mongodb.internal.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.OperationHelper.withReleasableConnection(OperationHelper.java:621)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:185)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:76)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:187)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1009)
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1000)
	at com.mongodb.client.internal.MongoCollectionImpl.updateMany(MongoCollectionImpl.java:646)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doUpdate$19(MongoTemplate.java:1638)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:553)
	... 51 common frames omitted
```

I also tried to upgrade from v1.7.2 to the next v1.7.3 version but faced the same issue.

My setup : 
- Appsmith deployed with Docker on a Swarm cluster
- Mongodb 4.0.28

### Steps To Reproduce

1. Install Appsmith v1.7.2 with docker and docker-compose
2. Confirm that the app is running well
3. Try to upgrade to v1.7.3 or higher
4. The issue should appear

### Version

Self-hosted - v1.7.8

**Comment by sidhantgoel** [comment]
Hi @micael-pn, MongoDB version 4.0 is not supported by AppSmith, please upgrade it to version 4.2 and it should work without any issues.

**Comment by Nikhil-Nandagopal** [comment]
@micael-pn we're now closing this issue. Please do re-open it if you still face a problem

**Comment by micael-pn** [comment]
Hi @Nikhil-Nandagopal 

Thank you for your input.

Do you have any compatibility data sheet for Mongodb and other dependencies ? We already commented on the issue regarding the compatibility with Mongodb 5.X : https://github.com/appsmithorg/appsmith/issues/11098

**Comment by sharat87** [comment]
@micael-pn, unfortunately no, but I can tell that recommended versions for MongoDB are 4.2 and 4.4, and for Redis is 6 or 7. Between these versions is where Appsmith works best today.
