### ISSUE TITLE
[Bug]: Wrong message is displayed when git push fails

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#15347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a git push is failed due to reasons other than upstream changes like a protected branch, the application displays there are upstream changes which is not correct.

![Screenshot 2022-07-15 at 13 58 23](https://user-images.githubusercontent.com/9128194/180142455-03107917-e70f-47df-89c7-7e55f863da41.png)

The expected behaviour is to display the actual error message why the push was rejected so that the user will be aware of that.

### Steps To Reproduce

1. Create an application and connect to git
2. Mark the branch as protected on GitHub
3. Make any changes and try to push those changes

### Version

1.7.8

**Comment by IAmAnubhavSaini** [comment]
@vishnu-gp What is the response from backend here?

**Comment by vishnu-gp** [comment]
> @vishnu-gp What is the response from backend here?

@IAmAnubhavSaini I think this has to be corrected from the BE and remove the pull button in FE in case of non-upstream changes related cases.

`{"responseMeta":{"status":400,"success":false,"error":{"code":4048,"message":"Looks like there are pending upstream changes. To prevent you from losing history, we will pull the changes and push them to your repo.","errorType":"GIT_UPSTREAM_CHANGES_PUSH_EXECUTION_ERROR","referenceDoc":"https://docs.appsmith.com/core-concepts/version-control-with-git/working-with-branches#syncing-local-with-remote-branch"}}}`

**Comment by Phylu** [comment]
I am having the same issue. This is really awful. We were debugging for two weeks to see what went wrong before seeing this issue. Here is the error message from the AppSmith logs, that shows no indication about the real reason:

```
backend stdout | com.appsmith.server.exceptions.AppsmithException: Looks like there are pending upstream changes. To prevent you from losing history, we will pull the changes and push them to your repo.
backend stdout | 	at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$pushApplication$58(GitServiceCEImpl.java:948)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#discardChanges(String, Boolean, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$pushApplication$58(GitServiceCEImpl.java:948)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:151)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152)
backend stdout | 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122)
backend stdout | 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122)
backend stdout | 		at reactor.core.publisher.MonoCurrentContext.subscribe(MonoCurrentContext.java:36)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
backend stdout | 		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
backend stdout | 		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
backend stdout | 		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout | 		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
backend stdout | 		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
backend stdout | 		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
backend stdout | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
backend stdout | 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
backend stdout | 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
backend stdout | 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
backend stdout | 		at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by IAmAnubhavSaini** [comment]
This code block here https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java#L939-L950 is checking only for the "rejected" case and not exactly why push was rejected. We need to implement sub-cases here for rejection.

```
.flatMap(tuple -> {
                    String pushResult = tuple.getT1();
                    Application application = tuple.getT2();
                    if (pushResult.contains("REJECTED")) {

                        return addAnalyticsForGitOperation(
                                AnalyticsEvents.GIT_PUSH.getEventName(),
                                application,
                                AppsmithError.GIT_UPSTREAM_CHANGES.getErrorType(),
                                AppsmithError.GIT_UPSTREAM_CHANGES.getMessage(),
                                application.getGitApplicationMetadata().getIsRepoPrivate()
                        )
                                .flatMap(application1 -> Mono.error(new AppsmithException(AppsmithError.GIT_UPSTREAM_CHANGES)));
                    }
                    return Mono.just(pushResult).zipWith(Mono.just(tuple.getT2()));
                })
```

@AnaghHegde @vishnu-gp
