### ISSUE TITLE
[Bug]: Appsmith server crash after change redis server

### ISSUE THREAD

**Issue by jmvizcainoio** [appsmithorg/appsmith#15359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are in the process to migrate our redis server ( standalone ) to a redis cluster using bitnami chart. 

The cluster is already configured and working fine, three masters with a replica per master. 

When i change the `APPSMITH_REDIS_URL` pointing to the new cluster Appsmith server fail. 

```
 - [55efbb1f-16]  500 Server Error for HTTP GET "/api/v1/users/me"
io.lettuce.core.RedisCommandExecutionException: MOVED 7335 100.96.28.7:6379
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.authentication.OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/v1/users/me" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
		at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
		at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:757)
		at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
		at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
		at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746)
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681)
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Unknown Source)
```

what is the way to configure appsmith to use a redis cluster and not standalone node ?

Thanks

### Steps To Reproduce

1. Install a redis cluster with 3 masters and 3 slaves
2. Config the APPSMITH_REDIS_URL
3. Try to login into appsmith

### Version

appsmith/appsmith-server:v1.7.3

**Comment by sharat87** [comment]
Hey @jmvizcainoio, thanks for reporting and sorry for the trouble caused. I'll try and see if I can reproduce this and get it resolved.

But, to unblock your instance, is it possible to test with a single Redis until then instead? Appsmith uses Redis _only_ for storing user session information, and the impact of losing data on Redis is that users would get logged out, and they can of course log back in. Not convenient, but this may be a viable solution for the time being. Once this is resolved, you can start using a cluster. Does that sound fine?

**Comment by jmvizcainoio** [comment]
> Hey @jmvizcainoio, thanks for reporting and sorry for the trouble caused. I'll try and see if I can reproduce this and get it resolved.
@sharat87 Thanks for your reply. Yes with redis standalone works fine. 
> 
> But, to unblock your instance, is it possible to test with a single Redis until then instead? Appsmith uses Redis _only_ for storing user session information, and the impact of losing data on Redis is that users would get logged out, and they can of course log back in. Not convenient, but this may be a viable solution for the time being. Once this is resolved, you can start using a cluster. Does that sound fine?

Great!! if only is used for save the sessions and is not critical, we can live without clustering.
