### ISSUE TITLE
[Bug]: server failed at start up, caused by: Error creating bean with name 'commonConfig': Unsatisfied dependency expressed through field 'isSignupDisabled'

### ISSUE THREAD

**Issue by winglight** [appsmithorg/appsmith#15919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I start up appsmith based on latest docker(in k8s cluster), the server failed and log as follows:
```
backend stdout |  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'segmentConfig' defined in URL [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/classes!/com/appsmith/server/configurations/SegmentConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'commonConfig': Unsatisfied dependency expressed through field 'isSignupDisabled'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
backend stdout | 
backend stdout |  - 
backend stdout | 
backend stdout | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
backend stdout | 
backend stdout |  - Application run failed
backend stdout | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'segmentConfig' defined in URL [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/classes!/com/appsmith/server/configurations/SegmentConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'commonConfig': Unsatisfied dependency expressed through field 'isSignupDisabled'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
backend stdout | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
backend stdout | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
backend stdout | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
backend stdout | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
backend stdout | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
backend stdout | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
backend stdout | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
backend stdout | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143)
backend stdout | 	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
backend stdout | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend stdout | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
backend stdout | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
backend stdout | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
backend stdout | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'commonConfig': Unsatisfied dependency expressed through field 'isSignupDisabled'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
backend stdout | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
backend stdout | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
backend stdout | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
backend stdout | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
backend stdout | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
backend stdout | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
backend stdout | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
backend stdout | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
backend stdout | 	... 26 common frames omitted
backend stdout | Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
backend stdout | 	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1328)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
backend stdout | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
backend stdout | 	... 41 common frames omitted
backend stdout | Caused by: java.lang.IllegalArgumentException: Invalid boolean value []
backend stdout | 	at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:154)
backend stdout | 	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429)
backend stdout | 	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402)
backend stdout | 	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
backend stdout | 	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
backend stdout | 	... 44 common frames omitted
backend stdout | 
2022-08-11 02:43:07,568 INFO exited: backend (exit status 1; not expected)
2022-08-11 02:43:08,569 INFO gave up: backend entered FATAL state, too many start retries too quickly
```

### Steps To Reproduce

Just after whole new installation of appsmith with helm in a k8s cluster, backend server failed to start up.

### Version

Self hosted 1.6.5

**Comment by winglight** [comment]
I fixed it by upgrading to 1.7.12.
