### ISSUE TITLE
[Bug]: Can't upgrade from 1.6.15

### ISSUE THREAD

**Issue by Mika64** [appsmithorg/appsmith#16249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try toupgrade appsmith from 1.6.15 to a newest version, I had this error (at login).

```
backend stdout | java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
backend stdout | 	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.ApplicationController#getAllApplicationsForHome() [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
backend stdout | 		at org.springframework.security.crypto.encrypt.AesBytesEncryptor.decrypt(AesBytesEncryptor.java:134)
backend stdout | 		at org.springframework.security.crypto.encrypt.HexEncodingTextEncryptor.decrypt(HexEncodingTextEncryptor.java:44)
backend stdout | 		at com.appsmith.server.services.ce.EncryptionServiceCEImpl.decryptString(EncryptionServiceCEImpl.java:32)
backend stdout | 		at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:237)
backend stdout | 		at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:246)
backend stdout | 		at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:246)
backend stdout | 		at com.appsmith.external.annotations.encryption.EncryptionMongoEventListener.onAfterConvert(EncryptionMongoEventListener.java:35)
backend stdout | 		at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:93)
backend stdout | 		at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
backend stdout | 		at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
backend stdout | 		at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
backend stdout | 		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
backend stdout | 		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
backend stdout | 		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
backend stdout | 		at org.springframework.data.mongodb.core.ReactiveMongoTemplate.maybeEmitEvent(ReactiveMongoTemplate.java:2606)
backend stdout | 		at org.springframework.data.mongodb.core.ReactiveMongoTemplate$ProjectingReadCallback.doWith(ReactiveMongoTemplate.java:3204)
backend stdout | 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:376)
backend stdout | 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
backend stdout | 		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:94)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
backend stdout | 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:207)
backend stdout | 		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:146)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
backend stdout | 		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout | 		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4232)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:104)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:56)
backend stdout | 		at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:73)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:755)
backend stdout | 		at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
backend stdout | 		at com.mongodb.internal.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:483)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:286)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:84)
backend stdout | 		at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:530)
backend stdout | 		at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:142)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:439)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:744)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:711)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:269)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:578)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:78)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:701)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:686)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:350)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.access$1200(NettyStream.java:104)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:409)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:406)
backend stdout | 		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout | 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
backend stdout | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout | 		at java.base/java.lang.Thread.run(Thread.java:829)
backend stdout | Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
backend stdout | 	at java.base/com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
backend stdout | 	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
backend stdout | 	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
backend stdout | 	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
backend stdout | 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
backend stdout | 	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:135)
backend stdout | 	at org.springframework.security.crypto.encrypt.AesBytesEncryptor.decrypt(AesBytesEncryptor.java:134)
backend stdout | 	at org.springframework.security.crypto.encrypt.HexEncodingTextEncryptor.decrypt(HexEncodingTextEncryptor.java:44)
backend stdout | 	at com.appsmith.server.services.ce.EncryptionServiceCEImpl.decryptString(EncryptionServiceCEImpl.java:32)
backend stdout | 	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:237)
backend stdout | 	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:246)
backend stdout | 	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:246)
backend stdout | 	at com.appsmith.external.annotations.encryption.EncryptionMongoEventListener.onAfterConvert(EncryptionMongoEventListener.java:35)
backend stdout | 	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:93)
backend stdout | 	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
backend stdout | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
backend stdout | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
backend stdout | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
backend stdout | 	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.maybeEmitEvent(ReactiveMongoTemplate.java:2606)
backend stdout | 	at org.springframework.data.mongodb.core.ReactiveMongoTemplate$ProjectingReadCallback.doWith(ReactiveMongoTemplate.java:3204)
backend stdout | 	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:376)
backend stdout | 	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
backend stdout | 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
backend stdout | 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
backend stdout | 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
backend stdout | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:94)
backend stdout | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
backend stdout | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
backend stdout | 	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 	at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:207)
backend stdout | 	at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:146)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
backend stdout | 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
backend stdout | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout | 	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
backend stdout | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4232)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:104)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:56)
backend stdout | 	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
backend stdout | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:165)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 	at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:73)
backend stdout | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 	at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:755)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
backend stdout | 	at com.mongodb.internal.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:483)
backend stdout | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:286)
backend stdout | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:84)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:530)
backend stdout | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:142)
backend stdout | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:439)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:744)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:711)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout | 	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout | 	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:269)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:578)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:78)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:701)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:686)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout | 	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout | 	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:350)
backend stdout | 	at com.mongodb.connection.netty.NettyStream.access$1200(NettyStream.java:104)
backend stdout | 	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:409)
backend stdout | 	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:406)
backend stdout | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
backend stdout | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
backend stdout | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
backend stdout | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
backend stdout | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
I've try many version and same result.
If I downgrade version to 1.6.15 (or oldest) in my docker-compose.yml, everything is OK.

### Steps To Reproduce

1. Run appsmith v1.6.15
2. upgrade in docker-compose.yml to newest vezrsion
3. login to appsmith

### Version

Self Hosted 1.6.15

**Comment by sharat87** [comment]
Hey @Mika64, sorry you are facing this trouble and thanks for reporting.

Can you describe what steps you've taken to upgrade your instance please?

The error you see usually occurs when the values of `APPSMITH_ENCRYPTION_SALT` or `APPSMITH_ENCRYPTION_PASSWORD` have changed. These two env variables are used to encrypt sensitive data in the database, things like database passwords. So, if these values are changed, then Appsmith won't be able to decrypt sensitive data in the database, and we see this error.

Can you confirm if either/both of these env variables have changed? If yes, can we restore them to what they were before? You can find them defined in the `stacks/configuration/docker.env` file on your server.

If this is not the problem, then can you share the full logs from your Docker container please? Thanks!

**Comment by Mika64** [comment]
Hello @sharat87,

> Can you describe what steps you've taken to upgrade your instance please?

I'm only edit my docker-compose.yml to use docker image version : 
appsmith/appsmith-ce:vX.Y.Z


> Can you confirm if either/both of these env variables have changed? If yes, can we restore them to what they were before? You can find them defined in the stacks/configuration/docker.env file on your server.

APPSMITH_ENCRYPTION_SALT and APPSMITH_ENCRYPTION_PASSWORD haven't changed and they in my docker-compose and correctly in docker.env.

> If this is not the problem, then can you share the full logs from your Docker container please? Thanks!

FYI : I removed my real mail address in log

[docker.log](https://github.com/appsmithorg/appsmith/files/9444169/docker.log)

**Comment by sharat87** [comment]
@Mika64, understood. Thanks for the information.

1. Since you say that the problem is resolved if you go back to version v1.6.15, do you have any special characters in any of your values in `docker.env`? Especially in `APPSMITH_ENCRYPTION_SALT` or `APPSMITH_ENCRYPTION_PASSWORD` or `APPSMITH_MONGODB_URI`?

2. I may be misunderstanding, but do you have the salt and password set in _both_ `docker-compose.yml` and the `docker.env` files? If yes, is there any particular reason for this? Can we comment them out in `docker-compose.yml`, and only keep the ones in `docker.env` and see if that resolves please?

**Comment by Mika64** [comment]
1. Yes, a lot of them ! ; : > , ^ % * & = ) < 
2. I have no reason for this (this is legacy ...)

When I remove APPSMITH_ENCRYPTION_SALT / APPSMITH_ENCRYPTION_PASSWORD from my docker-compose.yml, that's work perfectly.
Thanks a lot :)
