### ISSUE TITLE
[Bug]:  Appsmith fail when the mongodb is on cluster mode. 

### ISSUE THREAD

**Issue by jmvizcainoio** [appsmithorg/appsmith#16609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you run Appsmith using as backend a mondodb in replicaSet mode ( three nodes )  and one this stops , Appsmith is not to able continue running using the another two mongo servers.

```
[2022-09-07 08:38:36,843]  - Exception in monitor thread while connecting to server appsmith-mongocluster-2.appsmith-mongocluster-headless.appsmith.svc.cluster.local:27017
com.mongodb.MongoNodeIsRecoveringException: Command failed with error 91 (ShutdownInProgress): 'The server is in quiesce mode and will shut down' on server appsmith-mongocluster-2.appsmith-mongocluster-headless.appsmith.svc.cluster.local:27017. The full response is {"topologyVersion": {"processId": {"$oid": "63097a402d91880827b68dcd"}, "counter": 30}, "ok": 0.0, "errmsg": "The server is in quiesce mode and will shut down", "code": 91, "codeName": "ShutdownInProgress", "remainingQuiesceTimeMillis": 11, "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1662539905, "i": 119}}, "signature": {"hash": {"$binary": {"base64": "xxxxxxxx", "subType": "00"}}, "keyId": 7123087347838615554}}, "operationTime": {"$timestamp": {"t": 1662539905, "i": 119}}}
	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:266)
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:194)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342)
	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:96)
	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:44)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:131)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:73)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:182)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152)
	at java.base/java.lang.Thread.run(Unknown Source)
[2022-09-07 08:38:36,844]  - Exception in monitor thread while connecting to server appsmith-mongocluster-2.appsmith-mongocluster-headless.appsmith.svc.cluster.local:27017
```

### Steps To Reproduce

1. Install mongodb using bitnami helm chart 

```yaml
mongocluster:
  enabled: true
  architecture: replicaset
  useStatefulSet: true
  auth:
    enabled: true
    database: "appsmith"
    username: "appsmith"
    rootPassword: "root_password"
    password: "password"
    mongodb-replica-set-key: "key"
  replicaCount: 3
```

2. Execute appsmith 1.7.14
`  APPSMITH_MONGODB_URI: mongodb://appsmith:password@appsmith-mongocluster-0.appsmith-mongocluster-headless,appsmith-mongocluster-1.appsmith-mongocluster-headless,appsmith-mongocluster-2.appsmith-mongocluster-headless/appsmith?replicaSet=rs0`

3. Set the mongodb statefulset replicas to 2.
4. Try to access Appsmith and create a new application. 

### Version

1.7.14

**Comment by sharat87** [comment]
@jmvizcainoio, hey, thanks for raising this, and sorry for the delay in getting back.

Just to make sure I understand this and we're on the same page, the problem is that Appsmith started with a MongoDB that had 3 replicas, and things are fine, but when MongoDB is scaled down to 2 replicas, Appsmith server is unable to cope with that change. Is this right? If yes, that's an interesting scenario!

**Comment by merqurio** [comment]
> @jmvizcainoio, hey, thanks for raising this, and sorry for the delay in getting back.
> 
> Just to make sure I understand this and we're on the same page, the problem is that Appsmith started with a MongoDB that had 3 replicas, and things are fine, but when MongoDB is scaled down to 2 replicas, Appsmith server is unable to cope with that change. Is this right? If yes, that's an interesting scenario!

Yes exactly, this happens quite a lot and we see ourselves restarting the server quite frequently
