### ISSUE TITLE
[Bug]: Cannot update from 1.8.5 to v1.8.7 Mongo Migration failed

### ISSUE THREAD

**Issue by osangenis** [appsmithorg/appsmith#18116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I upgrade Docker image appsmith/appsmith-ce:v1.8.6 to v1.8.7 **mongo** fails to start.

The root cause seems to be:
```
Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin] : No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
```

There is a similar issue --> https://github.com/appsmithorg/appsmith/issues/17848

⚠️  the upgrade from  appsmith/appsmith-ce:v1.8.5 to  appsmith/appsmith-ce:v1.8.6 worked fine!! (tried after the failure)

### Steps To Reproduce

With mongo db and appsmith/appsmith-ce:v1.8.5, update Docker image to appsmith/appsmith-ce:v1.8.7

### Version

appsmith-ce:v1.8.7

**Comment by micael-pn** [comment]
Hello,

Same issue here when upgrading from 1.8.4 to 1.8.7

<details>
<summary>Stack trace</summary>

```
[2022-11-07 08:41:06,289]  - method[addTenantAdminPermissionsToInstanceAdmin] with arguments: [com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate, com.appsmith.server.helpers.PolicyUtils]
[2022-11-07 08:41:06,322]  - FAILED OVER - ChangeEntry{, "id"="add-tenant-admin-permissions-instance-admin", "author"="", "class"="DatabaseChangelog2", "method"="addTenantAdminPermissionsToInstanceAdmin"}
[2022-11-07 08:41:06,356]  - Mongock releasing the lock
[2022-11-07 08:41:06,365]  - Mongock released the lock
[2022-11-07 08:41:06,365]  - Mongock has finished
[2022-11-07 08:41:06,371]  - Error in mongock process. ABORTED MIGRATION
com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin] : No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockInitializingBeanRunner.afterPropertiesSet(MongockSpring5.java:84)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:194)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
	... 37 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1193)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1170)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2080)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1779)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:512)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:425)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:394)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:356)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2077)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:1280)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2049)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1779)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:512)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:425)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:394)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:356)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:292)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:288)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:107)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3207)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2822)
	at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2529)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:811)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:798)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.lambda$findOne$18(MongockTemplate.java:203)
	at com.github.cloudyrock.mongock.driver.api.lock.guard.invoker.LockGuardInvokerImpl.invoke(LockGuardInvokerImpl.java:18)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.findOne(MongockTemplate.java:203)
	at com.appsmith.server.migrations.DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin(DatabaseChangelog2.java:2643)
	... 45 common frames omitted
[2022-11-07 08:41:06,373]  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin] : No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
[2022-11-07 08:41:06,417]  - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: Disconnected
Caused by: java.util.concurrent.CancellationException: Disconnected
	at reactor.core.publisher.FluxPublish$PublishSubscriber.disconnectAction(FluxPublish.java:314)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.dispose(FluxPublish.java:305)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription$State.terminate(LettuceReactiveSubscription.java:303)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription.lambda$cancel$8(LettuceReactiveSubscription.java:187)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:238)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onComplete(RedisPublisher.java:896)
	at io.lettuce.core.RedisPublisher$State.onAllDataRead(RedisPublisher.java:698)
	at io.lettuce.core.RedisPublisher$State$3.read(RedisPublisher.java:608)
	at io.lettuce.core.RedisPublisher$State$3.onDataAvailable(RedisPublisher.java:565)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onDataAvailable(RedisPublisher.java:326)
	at io.lettuce.core.RedisPublisher$RedisSubscription.onAllDataRead(RedisPublisher.java:341)
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:778)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.pubsub.PubSubCommandHandler.completeCommand(PubSubCommandHandler.java:260)
	at io.lettuce.core.pubsub.PubSubCommandHandler.notifyPushListeners(PubSubCommandHandler.java:220)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:646)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
[2022-11-07 08:41:10,677]  - 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2022-11-07 08:41:10,719]  - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin] : No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin] : No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockInitializingBeanRunner.afterPropertiesSet(MongockSpring5.java:84)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 23 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:194)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
	... 37 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant com.appsmith.server.acl.AclPermission.READ_PERMISSION_GROUPS
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1193)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1170)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2080)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1779)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:512)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:425)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:394)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:356)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2077)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:1280)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2049)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1779)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:512)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:425)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:394)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:356)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:292)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:288)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:107)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3207)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2822)
	at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2529)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:811)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:798)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.lambda$findOne$18(MongockTemplate.java:203)
	at com.github.cloudyrock.mongock.driver.api.lock.guard.invoker.LockGuardInvokerImpl.invoke(LockGuardInvokerImpl.java:18)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate.findOne(MongockTemplate.java:203)
	at com.appsmith.server.migrations.DatabaseChangelog2.addTenantAdminPermissionsToInstanceAdmin(DatabaseChangelog2.java:2643)
	... 45 common frames omitted
```
</details>

Regards

**Comment by pranavkanade** [comment]
@micael-pn can you please upgrade to v1.8.8? We've released a patch fix for this issue.

**Comment by micael-pn** [comment]
Hello @pranavkanade 

I confirm that we were able to upgrade to v1.8.8. Thank you for your help !

Regards
