### ISSUE TITLE
[Bug]: NPE causes server crash

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#20203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

a user reported regular server crashes.

### Steps To Reproduce

Logs - 
```
java.lang.NullPointerException: The iterator returned a null value
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
*__checkpoint ⇢ Handler com.appsmith.server.controllers.LayoutController#updateLayout(String, String, String, Layout, String) [DispatcherHandler]
Original Stack Trace:
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:322)
at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
```

### Version

latest

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_732bw)

**Comment by pranavkanade** [comment]
Internal convo - https://theappsmith.slack.com/archives/C0341RERY4R/p1674651931241109
