### ISSUE TITLE
[Bug]: CI failure: Merge randomly failing on Git connected with JSLib Installed change

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in CI, where on merging child branch to master, merge api fails making test flaky, this is not always reproducible manually.
<img width="1440" alt="Screenshot 2023-03-03 at 11 45 55 AM" src="https://user-images.githubusercontent.com/80334441/222645651-c8ec6db2-c83f-413d-85ad-f7325a824080.png">

### Steps To Reproduce

1. Connect an app to git
2. Add js library and commit changes
3. Create new branch and add js library, commit changes
4. Merge child branch to master, observe it doesnt go through  

### Environment

Release

### Version

Release

**Comment by Aishwarya-U-R** [comment]
@Parthvi12 - Download video/logs from Cypress Dashboard/Git & attach it here for debugging reference.

**Comment by Aishwarya-U-R** [comment]
Attaching debug logs:

https://user-images.githubusercontent.com/91450662/222646577-30b5485c-8926-4c18-9f50-6c52927bd47b.mp4

[dockerlogs-10.zip](https://github.com/appsmithorg/appsmith/files/10878793/dockerlogs-10.zip)

**Comment by nayan-rafiq** [comment]
Here is the error message from log: 
```
backend stdout | [2023-03-02 09:10:39,607] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=boundedElastic-8, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - boundedElastic-8: Merge branch  feat/tempBranchd9336607 on master
backend stdout | 
backend stdout | [2023-03-02 09:10:39,622] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=boundedElastic-8, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - Execute time: JGIT git_merge, appId 640067b92f7ced7e90d7a9bf, Time elapsed: 15ms
backend stdout | 
backend stdout | [2023-03-02 09:10:39,625] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=boundedElastic-9, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - boundedElastic-9: Switching to the branch master
backend stdout | 
backend stdout | [2023-03-02 09:10:39,627] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=boundedElastic-9, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - Execute time: FS reconstruct application, Time elapsed: 4ms
backend stdout | 
backend stdout | [2023-03-02 09:10:39,661] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=nioEventLoopGroup-3-4, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - Error while importing the application 
backend stdout | 
backend stdout | [2023-03-02 09:10:39,680] userEmail=testowner@appsmith.com, sessionId=24ee2bf9-53a4-443b-ba60-5d961bffc110, thread=nioEventLoopGroup-3-2, requestId=c661e2c3-eab4-4560-93c7-68d6843bcd0e - 
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to import application in workspace 640062bd2f7ced7e90d7a946, 
backend stdout | 	at com.appsmith.server.solutions.ce.ImportExportApplicationServiceCEImplV2.lambda$importApplicationInWorkspace$78(ImportExportApplicationServiceCEImplV2.java:1249)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#merge(String, GitMergeDTO) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.solutions.ce.ImportExportApplicationServiceCEImplV2.lambda$importApplicationInWorkspace$78(ImportExportApplicationServiceCEImplV2.java:1249)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onError(MonoCollect.java:135)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2210)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:108)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842)
backend stdout | 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
backend stdout | 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
backend stdout | 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:863)
backend stdout | 		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:990)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2210)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredError(MonoUsingWhen.java:277)
backend stdout | 		at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475)
backend stdout | 		at reactor.core.publisher.Operators.complete(Operators.java:137)
backend stdout | 		at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
backend stdout | 		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onError(FluxUsingWhen.java:364)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
backend stdout | 		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:108)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.Operators.error(Operators.java:198)
backend stdout | 		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326)
backend stdout | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onError(FluxConcatMapNoPrefetch.java:220)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:474)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:802)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.error(FluxCreate.java:747)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:237)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.error(FluxCreate.java:189)
backend stdout | 		at reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:155)
backend stdout | 		at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:150)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
backend stdout | 		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$31(MongoOperationPublisher.java:573)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:94)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
backend stdout | 		at com.mongodb.internal.async.function.RetryingAsyncCallbackSupplier$RetryingCallback.onResult(RetryingAsyncCallbackSupplier.java:111)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
backend stdout | 		at com.mongodb.internal.operation.FindOperation$1.onResult(FindOperation.java:373)
backend stdout | 		at com.mongodb.internal.operation.CommandOperationHelper.lambda$transformingReadCallback$10(CommandOperationHelper.java:323)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$1.onResult(DefaultServer.java:238)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:82)
backend stdout | 		at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:683)
backend stdout | 		at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:159)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:46)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:526)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:501)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:824)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:788)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:648)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:645)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:319)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:266)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:645)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:89)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:778)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:763)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:648)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:645)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:319)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:347)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.access$1100(NettyStream.java:105)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:421)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:418)
backend stdout | 		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout | 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
backend stdout | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
backend stdout | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout | 		at java.base/java.lang.Thread.run(Thread.java:833)
backend stdout | 

```

**Comment by nayan-rafiq** [comment]
Here are recent logs from the CI: 
```
backend stdout | [2023-03-20 19:40:10,670] userEmail=testowner@appsmith.com, sessionId=532cf1c1-39d0-4a4a-afc8-a7566cfe7960, thread=boundedElastic-8, requestId=77e11b67-54e2-40e6-a14b-64502c2b7093 - boundedElastic-8: Switching to the branch master
backend stdout | 
backend stdout | [2023-03-20 19:40:10,673] userEmail=testowner@appsmith.com, sessionId=532cf1c1-39d0-4a4a-afc8-a7566cfe7960, thread=boundedElastic-8, requestId=77e11b67-54e2-40e6-a14b-64502c2b7093 - Execute time: FS reconstruct application, Time elapsed: 11ms
backend stdout | 
backend stdout | [2023-03-20 19:40:10,690] userEmail=testowner@appsmith.com, sessionId=532cf1c1-39d0-4a4a-afc8-a7566cfe7960, thread=nioEventLoopGroup-3-3, requestId=77e11b67-54e2-40e6-a14b-64502c2b7093 - Error while importing the application, reason: Command failed with error 251 (NoSuchTransaction): 'Given transaction number 117 does not match any in-progress transactions. The active transaction number is 116' on server localhost:27017. The full response is {"errorLabels": ["TransientTransactionError"], "ok": 0.0, "errmsg": "Given transaction number 117 does not match any in-progress transactions. The active transaction number is 116", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1679341201, "i": 3}}, "signature": {"hash": {"$binary": {"base64": "4g8bXF/UCTklRstsfCzPVXTObPg=", "subType": "00"}}, "keyId": 7212709416791965702}}, "operationTime": {"$timestamp": {"t": 1679341201, "i": 3}}}
backend stdout | 
backend stdout | [2023-03-20 19:40:10,699] userEmail=testowner@appsmith.com, sessionId=532cf1c1-39d0-4a4a-afc8-a7566cfe7960, thread=nioEventLoopGroup-3-3, requestId=77e11b67-54e2-40e6-a14b-64502c2b7093 - 
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to import application in workspace 6418b64f8559182580fcb93b, 
backend stdout | 	at com.appsmith.server.solutions.ce.ImportExportApplicationServiceCEImplV2.lambda$importApplicationInWorkspace$78(ImportExportApplicationServiceCEImplV2.java:1249)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#merge(String, GitMergeDTO) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.solutions.ce.ImportExportApplicationServiceCEImplV2.lambda$importApplicationInWorkspace$78(ImportExportApplicationServiceCEImplV2.java:1249)
```

**Comment by nayan-rafiq** [comment]
`NoSuchTransaction` happens when the same resources is being modified in parallel by a transaction. We're guessing that this is happening due to a race condition in the import flow. As there is an ongoing task to refactor the import flow, we're pausing working on this for a while.

**Comment by ginilpg** [comment]
@sumitsum Seems like an issue with JsLib+Git. Can you please check this once?

**Comment by AnandiKulkarni** [comment]
defect is verified on release - cc @Parthvi12
