### ISSUE TITLE
[Bug]: /static/js/355.1361a5cb.chunk.js: file not found

### ISSUE THREAD

**Issue by honoru-washswat** [appsmithorg/appsmith#21277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Every time I edit or enter the menu, I get an error.
overall slower
```

"TypeError: Cannot read properties of undefined (reading 'disconnect')
    at https://bo-devel.washswat.com/static/js/355.1361a5cb.chunk.js:1:924176
    at Dc (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7766555)
    at https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7784688
    at ji (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7707009)
    at Rc (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7766151)
    at mc (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7757641)
    at https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7707232
    at https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7784688
    at ji (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7707009)
    at Gi (https://bo-devel.washswat.com/static/js/main.a0d7bf76.js:2:7707177)"
```

https://discord.com/channels/725602949748752515/1083258727102169128

https://user-images.githubusercontent.com/107019051/223932081-d4e06de4-2633-4928-b36e-97ec3fbceaf6.mp4

### Steps To Reproduce

Happened after updating to 1.9.10

### Environment

Production

### Issue video log

https://user-images.githubusercontent.com/107019051/223932081-d4e06de4-2633-4928-b36e-97ec3fbceaf6.mp4

### Version

host/1.9.10

**Comment by Nikhil-Nandagopal** [comment]
Hope this is now fixed. Let us know if you are still facing the issue
