### ISSUE TITLE
[Bug]: com.mongodb.MongoSecurityException occurs

### ISSUE THREAD

**Issue by JSpiner** [appsmithorg/appsmith#22191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to install self-hosted appsmith using docker.
I just followed docker-compose guideline,
I faced MongoCommandException like below.
```
backend stdout | Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:416)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340)
backend stdout | 	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:104)
backend stdout | 	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:48)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:230)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:137)
```

As a guide(https://docs.appsmith.com/help-and-support/troubleshooting-guide/deployment-errors#step-1-edit-mongodb-uri), I try to edit my `docker.env`. 
But what mongoDb information should I enter?
I have never even connected mongodb. If appsmith uses mongodb internally, I don't know the initial id/pw.

Even if I change the connection information in docker.env it is not affected.

### Steps To Reproduce

In ubuntu,

docker-compose.yml
```
version: "3"

services:
  app-admin:
    image: appsmith/appsmith-ce:v1.9.10
    ports:
      - "5002:80"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
```

```sh
$ docker-compose up -d
```

### Environment

Production

### Version

effected at latest

**Comment by JSpiner** [comment]
full logs

```
2023-04-09 09:30:38,864 INFO success: backend entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
backend stdout | [2023-04-09 09:30:38,914]  - 
backend stdout | 
backend stdout | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
backend stdout | 
backend stdout | [2023-04-09 09:30:38,925]  - Application run failed
backend stdout | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='appsmith', source='appsmith', password=<hidden>, mechanismProperties=<hidden>}
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
backend stdout | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
backend stdout | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
backend stdout | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
backend stdout | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
backend stdout | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
backend stdout | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
backend stdout | 	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend stdout | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend stdout | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
backend stdout | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
backend stdout | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
backend stdout | Caused by: io.mongock.api.exception.MongockException: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='appsmith', source='appsmith', password=<hidden>, mechanismProperties=<hidden>}
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:67)
backend stdout | 	at io.mongock.runner.springboot.base.MongockInitializingBeanRunner.afterPropertiesSet(MongockInitializingBeanRunner.java:17)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
backend stdout | 	... 23 common frames omitted
backend stdout | Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='appsmith', source='appsmith', password=<hidden>, mechanismProperties=<hidden>}
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:276)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:139)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.access$100(SaslAuthenticator.java:50)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:65)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:59)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:283)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:59)
backend stdout | 	at com.mongodb.internal.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:56)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticate(InternalStreamConnectionInitializer.java:210)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.finishHandshake(InternalStreamConnectionInitializer.java:84)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:188)
backend stdout | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:54)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:534)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openWithConcurrencyLimit(DefaultConnectionPool.java:910)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$OpenConcurrencyLimiter.openOrGetAvailable(DefaultConnectionPool.java:851)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:177)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:166)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:97)
backend stdout | 	at com.mongodb.internal.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:173)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:373)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.lambda$execute$2(ListIndexesOperation.java:130)
backend stdout | 	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:141)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:73)
backend stdout | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:133)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:37)
backend stdout | 	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.getResidualKeys(MongoSync4RepositoryBase.java:73)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.isIndexFine(MongoSync4RepositoryBase.java:62)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:49)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:40)
backend stdout | 	at io.mongock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:50)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.initializationAndValidation(MigrateExecutorBase.java:420)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:88)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
backend stdout | 	... 26 common frames omitted
backend stdout | Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:416)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340)
backend stdout | 	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:104)
backend stdout | 	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:48)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:230)
backend stdout | 	at com.mongodb.internal.connection.SaslAuthenticator.getNextSaslResponse(SaslAuthenticator.java:137)
backend stdout | 	... 65 common frames omitted

```

**Comment by Nikhil-Nandagopal** [comment]
@JSpiner does your setup have access to the internet or is it running an airgapped version?

**Comment by JSpiner** [comment]
@Nikhil-Nandagopal 
I fixed it myself.
This is has no relevance with https://docs.appsmith.com/help-and-support/troubleshooting-guide/deployment-errors#step-1-edit-mongodb-uri .

The problem is `- ./stacks:/appsmith-stacks` this folders permission is not granted.
I gave it permission 775, user-groups and it works fine.
This is my docker host problem. It doesn't matter with appsmith.

I think you can close the issue, but please check it.
