### ISSUE TITLE
[Bug]: craco build --config .\craco.build.config.js on windows10  error

### ISSUE THREAD

**Issue by jixianyihao** [appsmithorg/appsmith#24325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use master branch and tag v1.9.21, I use it:
in dir: `app/client`

yarn install got success，

but when I  perform： `craco build --config .craco.build.config.js`

It didn't success.  error info :

Creating an optimized production build...
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (D:\code\2023renew\appsmith\app\client\node_modules\@babel\types\lib\validators\generated\index.js:2794:35)
    at PluginPass.Program (D:\code\2023renew\appsmith\app\client\node_modules\babel-plugin-lodash\lib\index.js:102:44)
Failed to compile.

TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ErrorBoundaryProps | Readonly<ErrorBoundaryProps>): ErrorBoundary', gave the following error.
    Type 'string' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | FallbackRender | undefined'.
  Overload 2 of 2, '(props: ErrorBoundaryProps, context: any): ErrorBoundary', gave the following error.
    Type 'string' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | FallbackRender | undefined'.
    30 | function App() {
    31 |   return (
  > 32 |     <Sentry.ErrorBoundary fallback={"An error has occured"}>
       |                           ^^^^^^^^
    33 |       <Provider store={store}>
    34 |         <LayersContext.Provider value={Layers}>
    35 |           <ThemedAppWithProps />

### Steps To Reproduce

1. download this project
2. git checkout master or tag v1.9.21
3. yarn install 
4. craco build --config  craco.build.config.js

### Environment

Production

### Version

SelfHost

**Comment by KelvinOm** [comment]
@jixianyihao thank you for issue.

It seems that you are using the global version of craco instead of the local one. Please try to use this `yarn craco --max-old-space-size=7168 build --config craco.build.config.js` or just run [script](https://github.com/appsmithorg/appsmith/blob/release/app/client/package.json#L20) `yarn build`

P.S. `--max-old-space-size=7168` — without this, you will get an error `javascript heap out of memory`.

**Comment by KelvinOm** [comment]
Closing this issue. If the issue persists, please let me know.

**Comment by taurusC** [comment]
> [@jixianyihao](https://github.com/jixianyihao) thank you for issue.
> 
> It seems that you are using the global version of craco instead of the local one. Please try to use this `yarn craco --max-old-space-size=7168 build --config craco.build.config.js` or just run [script](https://github.com/appsmithorg/appsmith/blob/release/app/client/package.json#L20) `yarn build`
> 
> P.S. `--max-old-space-size=7168` — without this, you will get an error `javascript heap out of memory`.

I encountered the same issue when using `yarn build`. The type checking of TypeScript keeps failing. Could you please assist me?
