### ISSUE TITLE
[Bug]: Unable to connect Appsmith application to git

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#24652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to connect one of my existing application to git unable to do so and getting following error:
```
appsmith backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to import application in workspace 646615274f39ee4d532a9ee8. Error: Cannot invoke "Object.getClass()" because "key" is null
```

```
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | [2023-06-20 04:57:09,907] userEmail=abhijeet@appsmith.com, sessionId=810eb319-8124-48e9-8d21-7974a1558150, thread=nioEventLoopGroup-3-16, requestId=13ad267deb9b34615cdc05f5b98bf9b9 - Error importing application. Error: Error: Cannot invoke "Object.getClass()" because "key" is null
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "key" is null
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeMapInternal(MappingMongoConverter.java:1146)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.createMap(MappingMongoConverter.java:1064)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writePropertyInternal(MappingMongoConverter.java:950)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeProperties(MappingMongoConverter.java:894)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:869)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writePropertyInternal(MappingMongoConverter.java:1003)
Tuesday, Jun 20th 2023, 10:27am
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeProperties(MappingMongoConverter.java:894)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:869)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:842)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:792)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:121)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.EntityOperations$MappedEntity.toMappedDocument(EntityOperations.java:655)
Jun 20 10:27:09 internalappsmith-5797bb74cc-xjbxp appsmith backend stdout | 	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$doSave$56(ReactiveMongoTemplate.java:1428)
```

https://app.mezmo.com/8c1d4711f3/logs/view?t=timestamp%3A1687237029912&a=1687237029912.1624189823919112235&hosts=internalappsmith-5797bb74cc-xjbxp&apps=appsmith

### Steps To Reproduce

1. Open https://internal.appsmith.com/app/license-key-manager-testing/create-license-646615314f39ee4d532a9ef9
2. Try to connect application via Git
3. Connect call ends up with following error 
<img width="635" alt="Screenshot 2023-06-20 at 10 46 01 AM" src="https://github.com/appsmithorg/appsmith/assets/41686026/d5515bc4-a126-4618-a61f-b64c0b709012">

### Environment

Production

### Version

Appsmith Business v1.9.23

**Comment by AnaghHegde** [comment]
@abhvsn Can you please invite me to this Application?

**Comment by abhvsn** [comment]
@AnaghHegde I think someone has deleted the app as apart of cleanup 😔.

**Comment by AnaghHegde** [comment]
Closing this as we don't have an option to reproduce the issue.
