### ISSUE TITLE
[Bug]: Error: Internal server error while processing request while saving changes.

### ISSUE THREAD

**Issue by naveenthontepu** [appsmithorg/appsmith#25124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No changes in our application but we are getting Internal server error while saving any changes. 

```
Internal server error while processing request 
```

We are also seeing that the Save has failed.

Response for the Save API call:
```
{
    "responseMeta": {
        "status": 500,
        "success": false,
        "error": {
            "code": "AE-APP-5000",
            "title": "Internal server error",
            "message": "Internal server error while processing request",
            "errorType": "INTERNAL_ERROR"
        }
    },
    "errorDisplay": "AE-APP-5000: Internal server error while processing request"
}
```

This is the log in the console we are seeing.
```
ErrorSagas.tsx:252 Error: Internal server error while processing request
    at ErrorSagas.tsx:126:9
    at p (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at p (redux-saga-core.esm.js:1157:29)
    at c (redux-saga-core.esm.js:1251:7)
    at redux-saga-core.esm.js:481:7
    at br (redux-saga-core.esm.js:31:5)
    at Sr (redux-saga-core.esm.js:87:5)
    at Er (redux-saga-core.esm.js:46:5)
```

### Steps To Reproduce

1. Open the edit application.
2. Change something.
3. get the loader icon for saving.
4. Internal server error.

### Environment

Production

### Version

Self Hosted.

**Comment by pranavkanade** [comment]
@naveenthontepu could you please share a screen recording of this issue in action?

We'll also need to debug this better, could you please share the app with support@appsmith.com and send us an email linking this issue?

**Comment by pranavkanade** [comment]
As there is no further information available. I am closing this issue. I will reopen if necessary.
