### ISSUE TITLE
[Bug]: 本地源码部署错误

### ISSUE THREAD

**Issue by 2524268884** [appsmithorg/appsmith#26191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

我正在使用pageplug（中国版的appsmith）进行本地化的源码部署，但是当启动服务时，出现报错，不知道如何解决

`[2023-08-09 04:26:31,782]  - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog.clearRedisCache] : Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 68afb0bf8b01.c.methodot.com/<unresolved>:31922
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog.clearRedisCache] : Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 68afb0bf8b01.c.methodot.com/<unresolved>:31922
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70)
        at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
        at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
        at com.github.cloudyrock.spring.v5.MongockSpring5$MongockInitializingBeanRunner.afterPropertiesSet(MongockSpring5.java:84)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
        ... 21 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:194)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143)
        at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
        at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
        ... 35 common frames omitted
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 68afb0bf8b01.c.methodot.com/<unresolved>:31922
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1689)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1597)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1383)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1366)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:1117)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:509)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:103)
        at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:57)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:104)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.Flux.blockLast(Flux.java:2644)
        at com.appsmith.server.migrations.DatabaseChangelog.doClearRedisKeys(DatabaseChangelog.java:4461)
        at com.appsmith.server.migrations.DatabaseChangelog.clearRedisCache(DatabaseChangelog.java:4451)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 40 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Flux.blockLast(Flux.java:2645)
                ... 43 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 68afb0bf8b01.c.methodot.com/<unresolved>:31922
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
        at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330)
        at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
        ... 53 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Connection closed prematurely
        at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
        at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
`

### Steps To Reproduce

如上描述

### Environment

Deploy Preview

### Version

1.1

**Comment by Nikhil-Nandagopal** [comment]
Hello, it seems you are on a very old version of Appsmith. Please update to the latest version and let us know if the issue still persists
