### ISSUE TITLE
[Bug]:when redis URL contains password , server start with error  "NOAUTH Authentication required"

### ISSUE THREAD

**Issue by novembersky** [appsmithorg/appsmith#26820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I start appsmith server  , I see the error message blow:
`[2023-08-31 06:10:57,214]  - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationSuccessHandler' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\authentication\handlers\AuthenticationSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'forkExamplesWorkspaceServiceImpl' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\solutions\ForkExamplesWorkspaceServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 7: Error creating bean with name 'userServiceImpl' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\services\UserServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 23: Error creating bean with name 'rateLimitService' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\ratelimiting\RateLimitService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'apiBuckets' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'forkExamplesWorkspaceServiceImpl' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\solutions\ForkExamplesWorkspaceServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 7: Error creating bean with name 'userServiceImpl' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\services\UserServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 23: Error creating bean with name 'rateLimitService' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\ratelimiting\RateLimitService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'apiBuckets' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 18 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\services\UserServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 23: Error creating bean with name 'rateLimitService' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\ratelimiting\RateLimitService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'apiBuckets' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 32 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rateLimitService' defined in file [E:\project\appsmith\app\server\appsmith-server\target\classes\com\appsmith\server\ratelimiting\RateLimitService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'apiBuckets' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 46 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'apiBuckets' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 60 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'apiBuckets' threw exception with message: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 74 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'proxyManager' defined in class path resource [com/appsmith/server/ratelimiting/RateLimitConfig.class]: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:362)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$0.proxyManager(<generated>)
	at com.appsmith.server.ratelimiting.RateLimitConfig.lambda$apiBuckets$0(RateLimitConfig.java:55)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.appsmith.server.ratelimiting.RateLimitConfig.apiBuckets(RateLimitConfig.java:54)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$0.CGLIB$apiBuckets$1(<generated>)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$0.apiBuckets(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 75 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager]: Factory method 'proxyManager' threw exception with message: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 100 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to r-bp1n2oe0vvpxjmf6hc.redis.rds.aliyuncs.com/<unresolved>:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:350)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
	at io.github.bucket4j.redis.lettuce.cas.LettuceBasedProxyManager.builderFor(LettuceBasedProxyManager.java:79)
	at com.appsmith.server.ratelimiting.RateLimitConfig.proxyManager(RateLimitConfig.java:45)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$0.CGLIB$proxyManager$0(<generated>)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.appsmith.server.ratelimiting.RateLimitConfig$$SpringCGLIB$$0.proxyManager(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 101 common frames omitted
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required.
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:747)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:682)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

### Steps To Reproduce

1、update appsmith project to newest release branch
2、set APPSMITH_REDIS_URL to  URL with password like "redis://passwod@r-bp1n2xxxxx.redis.rds.aliyuncs.com:6379/3"
2、run /scripts/start-dev-server.sh

### Environment

Release

### Version

Self host

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 could you have a look at this?

**Comment by sharat87** [comment]
It looks like you're running Appsmith server from source, right? If yes, can you pull/merge the latest `release` branch into your working copy and try please? This was a problem that was noticed in the `release` branch, and was reverted a few days ago. Let us know if you still see the issue after pulling latest `release`.

Thanks.
