### ISSUE TITLE
[Bug]: MongoDB Error on Fresh install

### ISSUE THREAD

**Issue by luizeof** [appsmithorg/appsmith#27286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB Error on Fresh install

```

 stdout | [2023-09-13 22:13:08,961]  - MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "4.8.2"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "5.10.0-23-amd64"}, "platform": "Java/Eclipse Adoptium/17.0.8+7"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='appsmith', source='appsmith', password=<hidden>, mechanismProperties=<hidden>}, streamFactoryFactory=NettyStreamFactoryFactory{eventLoopGroup=io.netty.channel.nio.NioEventLoopGroup@32b112a1, socketChannelClass=class io.netty.channel.socket.nio.NioSocketChannel, allocator=PooledByteBufAllocator(directByDefault: true), sslContext=null}, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@25b865b5], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@250b236d]}, clusterSettings={hosts=[localhost:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@67a056f1], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
backend stdout | 
backend stdout | [2023-09-13 22:13:08,994]  - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=REPLICA_SET_GHOST, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=35583531, setName='null', canonicalAddress=null, hosts=[], passives=[], arbiters=[], primary='null', tagSet=TagSet{[]}, electionId=null, setVersion=null, topologyVersion=TopologyVersion{processId=650233eb91d9b83060f8d50a, counter=0}, lastWriteDate=null, lastUpdateTimeNanos=1289565308103819}
backend stdout | 
backend stdout | [2023-09-13 22:13:09,025]  - Mongock runner COMMUNITY version[5.1.6]
backend stdout | 
backend stdout | [2023-09-13 22:13:09,025]  - Running Mongock with NO metadata
backend stdout | [2023-09-13 22:13:09,025]  - Property transaction-enabled not provided. It will become true as default in next versions. Set explicit value to false in case transaction are not desired.
backend stdout | [2023-09-13 22:13:09,026]  - Property transaction-enabled not provided and is unknown if driver is transactionable. BY DEFAULT MONGOCK WILL RUN IN NO-TRANSACTION MODE.
backend stdout | 
backend stdout | [2023-09-13 22:13:09,113]  - Reflections took 73 ms to scan 1 urls, producing 5 keys and 28 values
backend stdout | 
backend stdout | [2023-09-13 22:13:09,154]  - Reflections took 20 ms to scan 1 urls, producing 5 keys and 28 values
backend stdout | 
backend stdout | [2023-09-13 22:13:09,330]  - Error in mongock process. ABORTED MIGRATION
backend stdout | io.mongock.api.exception.MongockException: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:67)
backend stdout | 	at io.mongock.runner.springboot.base.MongockInitializingBeanRunner.afterPropertiesSet(MongockInitializingBeanRunner.java:17)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
backend stdout | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
backend stdout | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
backend stdout | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
backend stdout | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
backend stdout | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
backend stdout | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
backend stdout | 	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend stdout | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend stdout | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
backend stdout | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
backend stdout | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
backend stdout | Caused by: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:260)
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:194)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:416)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340)
backend stdout | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
backend stdout | 	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:75)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:293)
backend stdout | 	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:233)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.lambda$execute$1(ListIndexesOperation.java:133)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.lambda$execute$2(ListIndexesOperation.java:130)
backend stdout | 	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:141)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:73)
backend stdout | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:133)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:37)
backend stdout | 	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.getResidualKeys(MongoSync4RepositoryBase.java:73)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.isIndexFine(MongoSync4RepositoryBase.java:62)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:49)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:40)
backend stdout | 	at io.mongock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:50)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.initializationAndValidation(MigrateExecutorBase.java:420)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:88)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
backend stdout | 	... 26 common frames omitted
backend stdout | 
backend stdout | [2023-09-13 22:13:09,334]  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 
backend stdout | [2023-09-13 22:13:09,344]  - Operator called default onErrorDropped
backend stdout | reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: Disconnected
backend stdout | Caused by: java.util.concurrent.CancellationException: Disconnected
backend stdout | 	at reactor.core.publisher.FluxPublish$PublishSubscriber.disconnectAction(FluxPublish.java:327)
backend stdout | 	at reactor.core.publisher.FluxPublish$PublishSubscriber.dispose(FluxPublish.java:318)
backend stdout | 	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription$State.terminate(LettuceReactiveSubscription.java:271)
backend stdout | 	at org.springframework.data.redis.connection.lettuce.LettuceReactiveSubscription.lambda$cancel$8(LettuceReactiveSubscription.java:149)
backend stdout | 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
backend stdout | 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
backend stdout | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
backend stdout | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:238)
backend stdout | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250)
backend stdout | 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
backend stdout | 	at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onComplete(RedisPublisher.java:900)
backend stdout | 	at io.lettuce.core.RedisPublisher$State.onAllDataRead(RedisPublisher.java:702)
backend stdout | 	at io.lettuce.core.RedisPublisher$State$3.read(RedisPublisher.java:612)
backend stdout | 	at io.lettuce.core.RedisPublisher$State$3.onDataAvailable(RedisPublisher.java:569)
backend stdout | 	at io.lettuce.core.RedisPublisher$RedisSubscription.onDataAvailable(RedisPublisher.java:326)
backend stdout | 	at io.lettuce.core.RedisPublisher$RedisSubscription.onAllDataRead(RedisPublisher.java:341)
backend stdout | 	at io.lettuce.core.RedisPublisher$SubscriptionCommand.doOnComplete(RedisPublisher.java:782)
backend stdout | 	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:65)
backend stdout | 	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
backend stdout | 	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:747)
backend stdout | 	at io.lettuce.core.pubsub.PubSubCommandHandler.complete(PubSubCommandHandler.java:167)
backend stdout | 	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:682)
backend stdout | 	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112)
backend stdout | 	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:599)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
backend stdout | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
backend stdout | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
backend stdout | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout | 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
backend stdout | 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
backend stdout | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
backend stdout | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
backend stdout | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout | 	at java.base/java.lang.Thread.run(Thread.java:833)
backend stdout | 
2023-09-13 22:13:10,346 INFO success: mongodb entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
backend stdout | [2023-09-13 22:13:13,528]  - 
backend stdout | 
backend stdout | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
backend stdout | 
backend stdout | [2023-09-13 22:13:13,542]  - Application run failed
backend stdout | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
backend stdout | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
backend stdout | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
backend stdout | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
backend stdout | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
backend stdout | 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
backend stdout | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
backend stdout | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
backend stdout | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
backend stdout | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
backend stdout | 	at com.appsmith.server.ServerApplication.main(ServerApplication.java:15)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend stdout | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend stdout | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend stdout | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
backend stdout | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
backend stdout | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
backend stdout | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
backend stdout | Caused by: io.mongock.api.exception.MongockException: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:67)
backend stdout | 	at io.mongock.runner.springboot.base.MongockInitializingBeanRunner.afterPropertiesSet(MongockInitializingBeanRunner.java:17)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
backend stdout | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
backend stdout | 	... 23 common frames omitted
backend stdout | Caused by: com.mongodb.MongoNodeIsRecoveringException: Command failed with error 13436 (NotPrimaryOrSecondary): 'node is not in primary or recovering state' on server localhost:27017. The full response is {"topologyVersion": {"processId": {"$oid": "650233eb91d9b83060f8d50a"}, "counter": 0}, "ok": 0.0, "errmsg": "node is not in primary or recovering state", "code": 13436, "codeName": "NotPrimaryOrSecondary"}
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:260)
backend stdout | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:194)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:416)
backend stdout | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340)
backend stdout | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
backend stdout | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
backend stdout | 	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85)
backend stdout | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:75)
backend stdout | 	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:293)
backend stdout | 	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:233)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.lambda$execute$1(ListIndexesOperation.java:133)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
backend stdout | 	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.lambda$execute$2(ListIndexesOperation.java:130)
backend stdout | 	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:141)
backend stdout | 	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:73)
backend stdout | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:133)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
backend stdout | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:37)
backend stdout | 	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.getResidualKeys(MongoSync4RepositoryBase.java:73)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.isIndexFine(MongoSync4RepositoryBase.java:62)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:49)
backend stdout | 	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:40)
backend stdout | 	at io.mongock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:50)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.initializationAndValidation(MigrateExecutorBase.java:420)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:88)
backend stdout | 	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
backend stdout | 	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
backend stdout | 	... 26 common frames omitted
backend stdout | 
editor stdout | 127.0.0.1 - - [13/Sep/2023:22:13:17 +0000] "GET / HTTP/1.1" 200 2050 "-" "curl/7.68.0"
editor stdout | 
2023-09-13 22:13:19,905 INFO success: backend entered RUNNING state, process has stayed up for > than 20 seconds (startsecs)
editor stdout | 127.0.0.1 - - [13/Sep/2023:22:13:32 +0000] "GET / HTTP/1.1" 200 2050 "-" "curl/7.68.0"
editor stdout | 
editor stdout | 127.0.0.1 - - [13/Sep/2023:22:13:47 +0000] "GET / HTTP/1.1" 200 2050 "-" "curl/7.68.0"
editor stdout | 
editor stdout | 127.0.0.1 - - [13/Sep/2023:22:14:02 +0000] "GET / HTTP/1.1" 200 2050 "-" "curl/7.68.0"
editor stdout | 
editor stdout | 
```

### Steps To Reproduce

1. Setup with Docker Stack

### Environment

Production

### Version

latest

**Comment by Nikhil-Nandagopal** [comment]
@luizeof this seems to be working for me, did you follow this guide?
https://docs.appsmith.com/getting-started/setup/installation-guides/docker
We also had a bad release on Friday so maybe that contributed to this. Could you try to remove the older docker image, and docker compose file and try to follow the steps again? 
Feel free to re-open this if you are still facing this issue
