### ISSUE TITLE
[Bug]: 打开应用出错

### ISSUE THREAD

**Issue by cylgdzz111** [appsmithorg/appsmith#27602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1.当我点击应用的edit时 弹出Internal server error while processing request

### Steps To Reproduce

1.删除user表中的一个用户
2.删除permissGroup中assignedToUserIds关联的uid
3.打开应用报错，日志如下
4.恢复数据库备份，清除redis缓存，还是出现相同的错误

 userEmail=cuiyunlong1_wb@qiyi.com, sessionId=eca2fbdb-882c-4ea0-adb7-3c321506bd92, thread=lettuce-epollEventLoop-7-1, requestId=ad710fa3-daba-4521-a66a-79d5ea128cb9 - Going to get all unpublished action collections with params: {applicationId=[648028a07b69aa3516d7e17c]}, branch: null
[2023-09-26 01:53:09,207] userEmail=cuiyunlong1_wb@qiyi.com, sessionId=eca2fbdb-882c-4ea0-adb7-3c321506bd92, thread=lettuce-epollEventLoop-7-1, requestId=be85fd32-fc67-4c2a-8fc9-716b3b717184 - Going to get all actions with params: {applicationId=[648028a07b69aa3516d7e17c]}, branch: null
[2023-09-26 01:53:09,232] userEmail=cuiyunlong1_wb@qiyi.com, sessionId=eca2fbdb-882c-4ea0-adb7-3c321506bd92, thread=nioEventLoopGroup-3-4, requestId=be85fd32-fc67-4c2a-8fc9-716b3b717184 - 
java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
        at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler com.appsmith.server.controllers.ActionController#getAllUnpublishedActions(MultiValueMap, String) [DispatcherHandler]
Original Stack Trace:
                at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
                at org.springframework.security.crypto.encrypt.AesBytesEncryptor.decrypt(AesBytesEncryptor.java:134)
                at org.springframework.security.crypto.encrypt.HexEncodingTextEncryptor.decrypt(HexEncodingTextEncryptor.java:44)
                at com.appsmith.server.services.ce.EncryptionServiceCEImpl.decryptString(EncryptionServiceCEImpl.java:31)
                at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:234)
                at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:243)
                at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:243)
                at com.appsmith.external.annotations.encryption.EncryptionMongoEventListener.onAfterConvert(EncryptionMongoEventListener.java:35)
                at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:91)
                at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
                at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
                at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413)
                at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
                at org.springframework.data.mongodb.core.EntityLifecycleEventDelegate.publishEvent(EntityLifecycleEventDelegate.java:53)
                at org.springframework.data.mongodb.core.ReactiveMongoTemplate.maybeEmitEvent(ReactiveMongoTemplate.java:2379)
                at org.springframework.data.mongodb.core.ReactiveMongoTemplate$ProjectingReadCallback.doWith(ReactiveMongoTemplate.java:2961)
                at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)

### Environment

Production

### Version

self hosted 1.9.20

**Comment by cylgdzz111** [comment]
一开始启动应用时，没有设置过环境变量APPSMITH_ENCRYPTION_SALT，APPSMITH_ENCRYPTION_SALT

**Comment by cylgdzz111** [comment]
新建workspace没有问题，但是老的workspace里面的应用就打不开
