### ISSUE TITLE
Error on running from newly deployed Heroku app

### ISSUE THREAD

**Issue by ChrisBeeson** [appsmithorg/appsmith#2917]
## Description

running from heroku raises H10 error

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

Go to the documents page for deploying to heroku. [link](https://docs.appsmith.com/setup/heroku)

Press the deploy to heroku button.

in the config file I only entered the credentials hash and the salt and the path to mongodb (running on atlas)

Says it deploys ok, but when you visit the site it crashes (see log below)

### Important Details
 - Version: Heroku
 - OS: [MacOSX
 - Browser Chrome

log output: 
```
2021-02-09T02:14:13.535974+00:00 app[web.1]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2021-02-09T02:14:13.535974+00:00 app[web.1]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2021-02-09T02:14:13.535975+00:00 app[web.1]: 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2021-02-09T02:14:13.535975+00:00 app[web.1]: 	... 105 common frames omitted
2021-02-09T02:14:13.774132+00:00 heroku[web.1]: Process exited with status 1
2021-02-09T02:14:13.844667+00:00 heroku[web.1]: State changed from up to crashed
2021-02-09T02:17:16.000000+00:00 app[heroku-redis]: source=APPSMITH_REDIS addon=redis-rigid-54692 sample#active-connections=1 sample#load-avg-1m=0.725 sample#load-avg-5m=1.165 sample#load-avg-15m=1.125 sample#read-iops=0 sample#write-iops=0.0125 sample#memory-total=15629048kB sample#memory-free=9205288kB sample#memory-cached=3658440kB sample#memory-redis=326584bytes sample#hit-rate=1 sample#evicted-keys=0
2021-02-09T02:17:16.000000+00:00 app[heroku-redis]: source=APPSMITH_REDIS addon=redis-rigid-54692 sample#active-connections=1 sample#load-avg-1m=0.65 sample#load-avg-5m=0.91 sample#load-avg-15m=1.035 sample#read-iops=0 sample#write-iops=0.083333 sample#memory-total=15629048kB sample#memory-free=9205352kB sample#memory-cached=3658844kB sample#memory-redis=326584bytes sample#hit-rate=1 sample#evicted-keys=0
2021-02-09T02:21:09.393988+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=chainedmonster-appsmith.herokuapp.com request_id=86ad5717-d73d-4002-8390-c9345cbae691 fwd="202.173.161.14" dyno= connect= service= status=503 bytes= protocol=https
2021-02-09T02:21:10.281499+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=chainedmonster-appsmith.herokuapp.com request_id=d237d1b3-6dd6-4369-bd52-1aa37434aa8a fwd="202.173.161.14" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by ChrisBeeson** [comment]
My mistake I supplied an invalid mongo url
