### ISSUE TITLE
[Bug]: AppSmith Upgrade Breaking App Compatibility

### ISSUE THREAD

**Issue by haranobuhardo** [appsmithorg/appsmith#30053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just updated my AppSmith docker image from 1.9.39 to 1.9.57 (latest version). There's nothing unusual after the upgrade, but some of my created apps won't open and shows this error instead:
![image](https://github.com/appsmithorg/appsmith/assets/38966576/0e2f944f-51e7-48d3-9b23-9b9eb32edc7e)
`RTS server error while processing request: Error while migrating to latest DSL version`

This only shows in "edit" mode, but the app seems working just fine on deploy.

### Steps To Reproduce

Random app after upgraded AppSmith docker 1.9.39 to 1.9.57

### Environment

Production

### Version

1.9.57

**Comment by Nikhil-Nandagopal** [comment]
@haranobuhardo apologies you faced this. This PR fixes the issue.
https://github.com/appsmithorg/appsmith/pull/30046
It will be available in the next release
In the meantime, can I suggest you rollback if you have taken a backup?

**Comment by haranobuhardo** [comment]
> ou rollback if you have taken a backup?

I see, I didn't see that issue, I thought this was different

I've rollback. I will wait for the next version (>v1.9.57). Thanks!

**Comment by Nikhil-Nandagopal** [comment]
This will be available in the hotfix soon! Feel free to re-open the issue if it persists

**Comment by josueneo** [comment]
This still happens on > v1.9.58

Additional info, I am getting "Error fetching latest DSL version"

```
[2024-01-23 07:17:30,091] userEmail=admin@nospam.com, sessionId=d048b082-3eff-410f-9507-f5f60bd3bf18, thread=reactor-http-epoll-1, requestId=d20503e6-3e24-459f-8968-999779c40b22 - Error fetching latest DSL version
org.springframework.web.reactive.function.client.WebClientResponseException$Unauthorized: 401 Unauthorized from GET http://127.0.0.1:8080/rts-api/v1/dsl/version
        at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:310)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ? 401 UNAUTHORIZED from GET http://127.0.0.1:8080/rts-api/v1/dsl/version [DefaultWebClient]
Original Stack Trace:
                at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:310)
                at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:213)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
                at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
                at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
                at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onComplete(FluxFilterFuseable.java:171)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2072)
                at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
                at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
                at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431)
                at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:485)
                at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by janbre** [comment]
I got this error when upgrading from 1.9.57 to 1.29.

**Comment by Suyash254** [comment]
We have also facing a similar issue. After updating the version to 1.29. 
I will also attaching the error log in the thread
<img width="1440" alt="Screenshot 2024-07-09 at 2 43 15 PM" src="https://github.com/appsmithorg/appsmith/assets/175105305/7431dd84-d05f-4ab6-b085-d785c8f9295c">
![Screenshot 2024-07-09 at 2 30 07 PM](https://github.com/appsmithorg/appsmith/assets/175105305/804a6196-931e-4728-a1e5-35764554ea93)

**Comment by Nikhil-Nandagopal** [comment]
@janbre @Suyash254 can you try updating to 1.30. This was a known issue

**Comment by Suyash254** [comment]
@Nikhil-Nandagopal even after updating to 1.30 the error is still there
![Screenshot 2024-07-09 at 3 18 42 PM](https://github.com/appsmithorg/appsmith/assets/175105305/a3f781a2-454a-4574-b7a0-a07362d54bc5)

**Comment by nirkons** [comment]
Also updated from old version to 1.31 and experiencing this issue as well :(

**Comment by Nikhil-Nandagopal** [comment]
@nirkons @Suyash254 we're going to fix this in this PR 
https://github.com/appsmithorg/appsmith/pull/34905#pullrequestreview-2174592758
