### ISSUE TITLE
[Bug] Issues when trying to install

### ISSUE THREAD

**Issue by Ibrahim-Islam** [appsmithorg/appsmith#3049]
## Description

1. Typing a mongo password shows the following error:
![image](https://user-images.githubusercontent.com/6401874/107994341-0a9fd780-700f-11eb-8d67-91d778036818.png)

2. After the long wait, `appsmith_appsmith-internal-server_1` container fails with following
```
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

- Field 'id' cannot be empty

org.pf4j.PluginRuntimeException: Field 'id' cannot be empty

at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:874)

at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:796)

at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)

at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)

at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:61)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.base/java.lang.reflect.Method.invoke(Unknown Source)

at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)

at
```

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
Execute `./install.sh`

### Important Details
 - Version: 11.1
 - OS: MacOSX BigSur

**Comment by mohanarpit** [comment]
@sharat87 Can you push the fix for this issue to both, the master & release branches? More folks seem to have a different locale set.

**Comment by sharat87** [comment]
Pushed to release and cherry picked to master.

**Comment by mohanarpit** [comment]
@Ibrahim-Islam Can you try installing Appsmith once more by downloading the latest `install.sh` script as specified in our [Getting Started](https://docs.appsmith.com/setup/docker) docs?

If you still see a problem, please feel free to re-open this issue.

**Comment by Ibrahim-Islam** [comment]
@mohanarpit It works now. Thanks for the quick fix.

**Comment by koolay** [comment]
Need to fix in k8s's install.sh.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 is this a regression?

**Comment by sharat87** [comment]
@Nikhil-Nandagopal, not exactly a regression. We fixed it in the Docker installation script, but not in the Kubernetes installation script. Will do that now.
