### ISSUE TITLE
[Bug]: Error trying open existing app after upgrade

### ISSUE THREAD

**Issue by jmvizcainoio** [appsmithorg/appsmith#30602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Today i been upgraded appsmith to `1.9.61` version from `v1.9.25`  

We are using a external mondodb cluster and redis and we are using the 2.0.7 helm chart.
When appsmith server boot we got this errors. 

```
backend stdout |
backend stdout | [2024-01-24 14:39:23,226]  - Enabled plugins: []
backend stdout |
backend stdout | [2024-01-24 14:39:23,227]  - Disabled plugins: []
backend stdout |
backend stdout | [2024-01-24 14:39:23,234]  - PF4J version 3.10.0 in 'deployment' mode
backend stdout |
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'appsmithai-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'saas-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'google-sheets-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'js-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'oracle-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'smtp-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'amazons3-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'mysql-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'restapi-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,835]  - Plugin 'postgres-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'googleai-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'snowflake-plugin@1.0-SNAPSHOT' resolved
backend stdout |
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'anthropic-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'elasticsearch-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'mssql-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'redshift-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'databricks-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'mongo-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'graphql-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'aws-lambda-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'openai-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'dynamo-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'arangodb-plugin@1.0-SNAPSHOT' resolved
backend stdout |
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'redis-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Plugin 'firestore-plugin@1.0-SNAPSHOT' resolved
backend stdout | [2024-01-24 14:39:23,836]  - Start plugin 'appsmithai-plugin@1.0-SNAPSHOT'
...
backend stdout | [2024-01-24 14:39:24,240]  - Start plugin 'dynamo-plugin@1.0-SNAPSHOT'
backend stdout |
backend stdout | SLF4J: A SLF4J service provider failed to instantiate:
backend stdout | org.slf4j.spi.SLF4JServiceProvider: ch.qos.logback.classic.spi.LogbackServiceProvider not a subtype
backend stdout |
backend stdout | SLF4J: A SLF4J service provider failed to instantiate:
backend stdout | org.slf4j.spi.SLF4JServiceProvider: org.slf4j.reload4j.Reload4jServiceProvider not a subtype
backend stdout | SLF4J: No SLF4J providers were found.
backend stdout | SLF4J: Defaulting to no-operation (NOP) logger implementation
backend stdout | SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
backend stdout |
backend stdout | [2024-01-24 14:39:24,271]  - Start plugin 'arangodb-plugin@1.0-SNAPSHOT'
backend stdout |
backend stdout | [2024-01-24 14:39:24,276]  - Start plugin 'redis-plugin@1.0-SNAPSHOT'
backend stdout |
backend stdout | SLF4J: A SLF4J service provider failed to instantiate:
backend stdout | org.slf4j.spi.SLF4JServiceProvider: ch.qos.logback.classic.spi.LogbackServiceProvider not a subtype
backend stdout |
backend stdout | SLF4J: A SLF4J service provider failed to instantiate:
backend stdout | org.slf4j.spi.SLF4JServiceProvider: org.slf4j.reload4j.Reload4jServiceProvider not a subtype
backend stdout | SLF4J: No SLF4J providers were found.
backend stdout | SLF4J: Defaulting to no-operation (NOP) logger implementation
backend stdout | SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
...
```

And when i try to create a new application into appsmith i recieve this error. 

```
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to load datasource templates. Details: Cannot invoke "org.pf4j.PluginWrapper.getPluginClassLoader()" because the return value of "org.pf4j.PluginManager.getPlugin(String)" is null.
backend stdout | 	at com.appsmith.server.plugins.base.PluginServiceCEImpl.lambda$getTemplates$29(PluginServiceCEImpl.java:473)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.PluginController#getAll(MultiValueMap, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.plugins.base.PluginServiceCEImpl.lambda$getTemplates$29(PluginServiceCEImpl.java:473)
backend stdout | 		at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)

```

### Steps To Reproduce

When i try to create a new app or open an existing i get this error.

```
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to load datasource templates. Details: Cannot invoke "org.pf4j.PluginWrapper.getPluginClassLoader()" because the return value of "org.pf4j.PluginManager.getPlugin(String)" is null.
backend stdout | 	at com.appsmith.server.plugins.base.PluginServiceCEImpl.lambda$getTemplates$29(PluginServiceCEImpl.java:473)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.PluginController#getAll(MultiValueMap, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.plugins.base.PluginServiceCEImpl.lambda$getTemplates$29(PluginServiceCEImpl.java:473)
backend stdout | 		at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
backe
```

### Environment

Production

### Version

1.9.61

**Comment by mohanarpit** [comment]
@jmvizcainoio I'm sorry you are facing this issue. By any chance did you end up downgrading your instance after the upgrade? 

I'm asking this because Appsmith keeps shipping new integrations & plugins. The exception stack trace indicates that there are new plugins in the database, but no code to handle those plugins in the actual Docker image.

**Comment by DerLinne** [comment]
We are facing the same problem.

Is there any chance to solve this with downgrades?

**Comment by DerLinne** [comment]
Thank you for the repsonse - seems to work again 👍

**Comment by jmvizcainoio** [comment]
> @jmvizcainoio I'm sorry you are facing this issue. By any chance did you end up downgrading your instance after the upgrade?
> 
> I'm asking this because Appsmith keeps shipping new integrations & plugins. The exception stack trace indicates that there are new plugins in the database, but no code to handle those plugins in the actual Docker image. In order to resolve this, I would suggest either:
> 
> 1. Upgrade to v1.9.61 again & keep Appsmith instance running on this version.
> 2. If you have a DB backup for v1.9.25, use that DB backup to restart v1.9.25. Since this is a very old version, I would recommend you take this as a last resort because I am invested in you seeing the latest & greatest of this product. 😄

Hi @mohanarpit No, just upgrade. I'm using the latest docker image. I fixed restoring the mongodb database from a backup and now seems that everything is working fine. 

Thanks

**Comment by aryan26gupta** [comment]
I don't have this exact same issue, but I am shown the same error:
` Error: Unable to load datasource templates. Details: Cannot invoke "org.pf4j.PluginWrapper.getPluginClassLoader()" because the return value of "org.pf4j.PluginManager.getPlugin(String)" is null.`

This error modal pops up when I try to create a new application or edit an existing one from the home page. I am working on the appsmith[community edition] which I have self hosted via docker.
