### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nicolamarangoni** [appsmithorg/appsmith#30876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The container in which appsmith is running generates the following log entry every 2 minutes:
```
backend stdout | [2024-02-02 12:32:52,963] userEmail=anonymousUser, sessionId=, thread=reactor-http-nio-3, requestId=ab4f90cc-5f3f-4c2f-98cb-fe49d3895812 - Going to find action based on branchName and defaultActionId with id: 63d180b014c3b962795af5a4
backend stdout |
backend stdout | [2024-02-02 12:32:52,966] userEmail=anonymousUser, sessionId=, thread=nioEventLoopGroup-3-4, requestId=ab4f90cc-5f3f-4c2f-98cb-fe49d3895812 -
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to find action 63d180b014c3b962795af5a4,main
backend stdout |        at com.appsmith.server.newactions.base.NewActionServiceCEImpl.findByBranchNameAndDefaultActionId(NewActionServiceCEImpl.java:1583)
backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout |        *__checkpoint ⇢ Handler com.appsmith.server.controllers.ActionController#executeAction(Flux, String, String, String, ServerWebExchange) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout |                at com.appsmith.server.newactions.base.NewActionServiceCEImpl.findByBranchNameAndDefaultActionId(NewActionServiceCEImpl.java:1583)
backend stdout |                at com.appsmith.server.solutions.ce.ActionExecutionSolutionCEImpl.lambda$executeAction$1(ActionExecutionSolutionCEImpl.java:183)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
....
....
backend stdout |                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
backend stdout |                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
backend stdout |                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout |                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout |                at java.base/java.lang.Thread.run(Thread.java:840)
backend stdout |
```
It looks like it searches for the non-existing action 63d180b014c3b962795af5a4.

### Steps To Reproduce

Simply start the container with the existing application.

### Environment

Production

### Version

Self hosted - 1.10

**Comment by sharat87** [comment]
Hey @nicolamarangoni, thank you for reaching out. Can you share more logs around this please? Specifically, I'd like the see the HTTP request that triggered this, as logged by Caddy. It should start with `editor stdout |` in the logs.

**Comment by nicolamarangoni** [comment]
Hello, I don't find the error anymore in the last hours of the docker logs.
Which situations could trigger this kind of error? I got it before and shortly after the upgrade to the latest version.
You can close this issue.
Cheers
