### ISSUE TITLE
[Bug]: Error in upgrading from 1.8.13 to latest

### ISSUE THREAD

**Issue by zom-bee** [appsmithorg/appsmith#32588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I upgraded following directions provided on update page `docker-compose pull && docker-compose rm -fsv appsmith && docker-compose up -d`. 
After running `docker-compose up -d`, I get following error

[2024-04-11 06:07:11,428]  - method[executeMigration] with arguments: []
[2024-04-11 06:07:11,429]  - Check if performant query can be used.
[2024-04-11 06:07:11,542]  - FAILED OVER - {"id"="migrate-configurations-to-data-storage-v2", "type"="execution", "author"="default_author", "class"="Migration020TransferToDatasourceStorage", "method"="executeMigration"}
[2024-04-11 06:07:11,568]  - Mongock migration aborted and DB transaction not enabled. Starting manual rollback process
[2024-04-11 06:07:11,569]  - method[rollbackExecution] with arguments: []
[2024-04-11 06:07:11,571]  - ROLLED BACK - {"id"="migrate-configurations-to-data-storage-v2", "type"="execution", "author"="default_author", "class"="Migration020TransferToDatasourceStorage", "method"="executeMigration"}
[2024-04-11 06:07:11,583]  - Mongock releasing the lock
[2024-04-11 06:07:11,584]  - Mongock releasing the lock
[2024-04-11 06:07:11,601]  - Mongock released the lock
[2024-04-11 06:07:11,601]  - Mongock has finished
[2024-04-11 06:07:11,601]  - Error in mongock process. ABORTED MIGRATION
io.mongock.api.exception.MongockException: Error in method[Migration020TransferToDatasourceStorage.executeMigration] : Unable to invoke Cipher due to bad padding
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processExceptionOnChangeSetExecution(MigrateExecutorBase.java:398)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeSet(MigrateExecutorBase.java:207)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.loopRawChangeSets(MigrateExecutorBase.java:172)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(MigrateExecutorBase.java:162)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processChangeLogInTransactionIfApplies(MigrateExecutorBase.java:162)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeLog(MigrateExecutorBase.java:136)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processChangeLogs(MigrateExecutorBase.java:126)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.lambda$processMigration$1(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processMigration(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:103)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
	at io.mongock.runner.springboot.base.MongockInitializingBeanRunner.afterPropertiesSet(MongockInitializingBeanRunner.java:17)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.runChangeSet(ChangeLogRuntimeImpl.java:79)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeChangeSetMethod(MigrateExecutorBase.java:386)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeAndLogChangeSet(MigrateExecutorBase.java:244)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeSet(MigrateExecutorBase.java:205)
	... 38 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
	at org.springframework.security.crypto.encrypt.AesBytesEncryptor.decrypt(AesBytesEncryptor.java:134)
	at org.springframework.security.crypto.encrypt.HexEncodingTextEncryptor.decrypt(HexEncodingTextEncryptor.java:44)
	at com.appsmith.server.services.ce.EncryptionServiceCEImpl.decryptString(EncryptionServiceCEImpl.java:30)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:255)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:264)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:264)
	at com.appsmith.external.annotations.encryption.EncryptionMongoEventListener.onAfterConvert(EncryptionMongoEventListener.java:35)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:91)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.data.mongodb.core.EntityLifecycleEventDelegate.publishEvent(EntityLifecycleEventDelegate.java:53)
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:2207)
	at org.springframework.data.mongodb.core.MongoTemplate$ProjectingReadCallback.doWith(MongoTemplate.java:3106)
	at org.springframework.data.mongodb.core.MongoTemplate$CloseableIterableCursorAdapter.next(MongoTemplate.java:3319)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.springframework.data.util.IteratorSpliterator.forEachRemaining(IteratorSpliterator.java:88)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at com.appsmith.server.migrations.utils.CompatibilityUtils.optimizeQueryForNoCursorTimeout(CompatibilityUtils.java:30)
	at com.appsmith.server.migrations.db.ce.Migration020TransferToDatasourceStorage.executeMigration(Migration020TransferToDatasourceStorage.java:74)
	... 46 common frames omitted
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1395)
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:406)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:135)
	... 69 common frames omitted
[2024-04-11 06:07:11,627]  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Error in method[Migration020TransferToDatasourceStorage.executeMigration] : Unable to invoke Cipher due to bad padding
[2024-04-11 06:07:15,924]  - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
[2024-04-11 06:07:16,035]  - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Error in method[Migration020TransferToDatasourceStorage.executeMigration] : Unable to invoke Cipher due to bad padding
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at com.appsmith.server.ServerApplication.main(ServerApplication.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: io.mongock.api.exception.MongockException: Error in method[Migration020TransferToDatasourceStorage.executeMigration] : Unable to invoke Cipher due to bad padding
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processExceptionOnChangeSetExecution(MigrateExecutorBase.java:398)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeSet(MigrateExecutorBase.java:207)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.loopRawChangeSets(MigrateExecutorBase.java:172)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(MigrateExecutorBase.java:162)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processChangeLogInTransactionIfApplies(MigrateExecutorBase.java:162)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeLog(MigrateExecutorBase.java:136)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processChangeLogs(MigrateExecutorBase.java:126)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.lambda$processMigration$1(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processMigration(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:103)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
	at io.mongock.runner.springboot.base.MongockInitializingBeanRunner.afterPropertiesSet(MongockInitializingBeanRunner.java:17)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 23 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.runChangeSet(ChangeLogRuntimeImpl.java:79)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeChangeSetMethod(MigrateExecutorBase.java:386)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeAndLogChangeSet(MigrateExecutorBase.java:244)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeSet(MigrateExecutorBase.java:205)
	... 38 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:141)
	at org.springframework.security.crypto.encrypt.AesBytesEncryptor.decrypt(AesBytesEncryptor.java:134)
	at org.springframework.security.crypto.encrypt.HexEncodingTextEncryptor.decrypt(HexEncodingTextEncryptor.java:44)
	at com.appsmith.server.services.ce.EncryptionServiceCEImpl.decryptString(EncryptionServiceCEImpl.java:30)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:255)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:264)
	at com.appsmith.external.annotations.encryption.EncryptionHandler.convertEncryption(EncryptionHandler.java:264)
	at com.appsmith.external.annotations.encryption.EncryptionMongoEventListener.onAfterConvert(EncryptionMongoEventListener.java:35)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:91)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.data.mongodb.core.EntityLifecycleEventDelegate.publishEvent(EntityLifecycleEventDelegate.java:53)
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:2207)
	at org.springframework.data.mongodb.core.MongoTemplate$ProjectingReadCallback.doWith(MongoTemplate.java:3106)
	at org.springframework.data.mongodb.core.MongoTemplate$CloseableIterableCursorAdapter.next(MongoTemplate.java:3319)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.springframework.data.util.IteratorSpliterator.forEachRemaining(IteratorSpliterator.java:88)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at com.appsmith.server.migrations.utils.CompatibilityUtils.optimizeQueryForNoCursorTimeout(CompatibilityUtils.java:30)
	at com.appsmith.server.migrations.db.ce.Migration020TransferToDatasourceStorage.executeMigration(Migration020TransferToDatasourceStorage.java:74)
	... 46 common frames omitted
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1395)
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:406)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
	at org.springframework.security.crypto.encrypt.CipherUtils.doFinal(CipherUtils.java:135)
	... 69 common frames omitted
[2024-04-11 06:07:29,933]  - Cancelled mongock lock daemon

### Steps To Reproduce

1. Install 1.8.13
2. Add some workspaces
3. Upgrade to latest version 
4. Expected : AppSmith should start
5. Actual : It fails with above error 

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self Hosted 1.8.13 -> Latest

**Comment by pranavkanade** [comment]
@zom-bee This is not a bug. Upgrades to the latest from versions <1.9.2 are expected to fail. 

It is mentioned in our documentation. Please read more here - https://docs.appsmith.com/getting-started/setup/instance-management/update-appsmith#update-on-docker

You are expected to upgrade to v1.9.2 first and then upgrade to the latest. Read more - https://docs.appsmith.com/getting-started/setup/instance-management/upgrade-to-checkpoint-version
