### ISSUE TITLE
[Bug]: MySql datasource connection error - Authentication failed

### ISSUE THREAD

**Issue by alpacaca** [appsmithorg/appsmith#35253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I deploy appsmith in my local env and have running a long time stably.
Recently, I create a new connection to mysql and display the error:

Error Message: Authentication failed
Report Class: o.m.r.message.flow.AuthenticationFlow
Stack:
j.l.IndexOutOfBoundsException: readerIndex(63) + length(1) exceeds writerIndex(63): PooledSlicedByteBuf(ridx: 63, widx: 63, cap: 63/63, unwrapped: PooledUnsafeDirectByteBuf(ridx: 66, widx: 66, cap: 2048))
	at i.n.b.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at i.n.b.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
	at i.n.b.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
	at o.m.r.m.s.InitialHandshakePacket.decode(InitialHandshakePacket.java:100)
	at o.m.r.c.DecoderState$1.decode(DecoderState.java:25)
	at o.m.r.c.MariadbFrameDecoder.decode(MariadbFrameDecoder.java:104)
	at o.m.r.c.MariadbFrameDecoder.decode(MariadbFrameDecoder.java:93)
	at i.n.h.c.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at i.n.h.c.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	... 15 common frames omitted
Wrapped by: i.n.h.c.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(63) + length(1) exceeds writerIndex(63): PooledSlicedByteBuf(ridx: 63, widx: 63, cap: 63/63, unwrapped: PooledUnsafeDirectByteBuf(ridx: 66, widx: 66, cap: 2048))
	at i.n.h.c.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
	at i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	... 13 common frames omitted
Wrapped by: i.r.s.R2dbcNonTransientResourceException: Connection error
	at o.m.r.c.SimpleClient.handleConnectionError(SimpleClient.java:187)
	at o.m.r.c.SimpleClient.sendResumeError(SimpleClient.java:196)
	at o.m.r.c.SimpleClient.receiveResumeError(SimpleClient.java:203)
	at r.c.p.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at c.t.w.p.c.l.MdcContextLifter.onError(MdcContextLifter.java:35)
	at r.c.p.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at r.n.c.FluxReceive.terminateReceiver(FluxReceive.java:478)
	at r.n.c.FluxReceive.drainReceiver(FluxReceive.java:273)
	at r.n.c.FluxReceive.onInboundError(FluxReceive.java:466)
	at r.n.c.ChannelOperations.onInboundError(ChannelOperations.java:495)
	at r.n.c.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:144)
	at i.n.c.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at i.n.c.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at i.n.c.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at i.n.c.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at i.n.c.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at i.n.c.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at i.n.c.e.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at i.n.c.e.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at i.n.c.e.EpollEventLoop.run(EpollEventLoop.java:397)
	at i.n.u.c.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at i.n.u.c.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:840)

It sames like a netty error when connect by r2dbc

### Steps To Reproduce

Create mysql connection by  Datasources

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.9.21

**Comment by pranavkanade** [comment]
@alpacaca can you please upgrade to the latest to see if that help? Also, a screen recording would help in understanding exact steps to reproduce the issue. Is it happening during `connection test` or saving or creation etc.

**Comment by alpacaca** [comment]
> @alpacaca can you please upgrade to the latest to see if that help? Also, a screen recording would help in understanding exact steps to reproduce the issue. Is it happening during `connection test` or saving or creation etc.

@pranavkanade sorry, I have repackaged the front-end page and just use appsmith plugin backend, so screen recording cannot help.
Actually, it is happening during `connection test`.

I will try the latest version instead and reply soon.

**Comment by alpacaca** [comment]
I try on app.appsmith.com/app in my app, it also doesn't work ... here is the screenshot
![screenshot_appsmith](https://github.com/user-attachments/assets/ae2c7288-d585-4989-84eb-82ae9f476306)

and request curl copy:

```shell
curl 'https://app.appsmith.com/api/v1/datasources/test' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ajs_anonymous_id=598de59d-162e-41a3-a710-6804b59db718; _hjSessionUser_2952959=eyJpZCI6Ijc5MTRhZTMyLWJkOGMtNTY1ZS05MjI0LWJhNTA0NTU1NGM3MiIsImNyZWF0ZWQiOjE3MjIyNDU2NjUwMTAsImV4aXN0aW5nIjp0cnVlfQ==; _gcl_au=1.1.1654232351.1722245666; _ga=GA1.1.356015106.1722245666; SESSION=7bf1d513-42fa-4b41-91d2-8f6c61793265; intercom-device-id-y10e7138=4982bf1f-7c74-417a-90eb-1e6279eec1dc; ajs_user_id=craig.sese@gmail.com; _hjSession_2952959=eyJpZCI6IjMxYWJjN2I5LTczY2EtNGRhZC05OTY5LTkyYWM1OGUwOWEwZCIsImMiOjE3MjIyNTM4NDg0MzQsInMiOjEsInIiOjEsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjowLCJzcCI6MH0=; _ga_D1VS24CQXE=GS1.1.1722253846.2.0.1722253849.0.0.0; SL_C_23361dd035530_SID={"c370af0df0edf38360adbefbdc47d2b42ea137c9":{"sessionId":"meFwPGahFI_J9BcwRaEar","visitorId":"8UHRmHLrX0FD6AlJD6pG3"}}; intercom-session-y10e7138=UkZ4SHUrOWRUSUtTZkZHUzJxSzE4Z2NSNzEyc3JHK2tVeU0yTC9PR21qTEx6V1lScy92UlhGZVBrdU51QlQ1by0tSDBsbEROS2t4b2s0MlRsUElSWE9JZz09--53ad53c4e84f13df15c4f90144be0a4f2856508d' \
  -H 'Origin: https://app.appsmith.com' \
  -H 'Referer: https://app.appsmith.com/app/my-first-application/page1-64f7e9e149cf293c0e2f9a78/edit/datasource/temp-id-0?from=datasources&pluginId=5f192a44a2d05225d010db9d' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'X-Requested-By: Appsmith' \
  -H 'newrelic: eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjQyMDk1NDgiLCJhcCI6IjExMzQzODgzMDkiLCJpZCI6IjhlOWVmYzliNzhiOWZmM2EiLCJ0ciI6IjcxNDJiNGI0NzQ0MDU5OWE2MDAwMjM2M2UwNWU1MjdmIiwidGkiOjE3MjIyNTM5NDc1MzN9fQ==' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sentry-trace: 970bad5e3cf349b4864562131ed65ade-8826e65a5515406e-0' \
  -H 'traceparent: 00-7142b4b47440599a60002363e05e527f-8e9efc9b78b9ff3a-01' \
  -H 'tracestate: 4209548@nr=0-1-4209548-1134388309-8e9efc9b78b9ff3a----1722253947533' \
  -H 'x-anonymous-user-id: 598de59d-162e-41a3-a710-6804b59db718' \
  --data-raw '{"datasourceId":"","environmentId":"64f7e9df49cf293c0e2f9a72","datasourceConfiguration":{"properties":[null,{"key":"Connection method","value":"STANDARD"}],"connection":{"mode":"READ_WRITE","ssl":{"authType":"DEFAULT"}},"endpoints":[{"port":"3307","host":"146.56.222.244"}],"authentication":{"databaseName":"information_schema","username":"test","password":"123456"}},"pluginId":"5f192a44a2d05225d010db9d","workspaceId":"64f7e9df49cf293c0e2f9a6e"}'

```

**Comment by alpacaca** [comment]
@Nikhil-Nandagopal can reopen this issue?

**Comment by Nikhil-Nandagopal** [comment]
Sample app:
https://app.appsmith.com/app/my-first-application/page1-64f7e9e149cf293c0e2f9a78/edit/datasource/temp-id-0?from=datasources&pluginId=5f192a44a2d05225d010db9d
