### ISSUE TITLE
[Bug] Flaky issues with activity execution after HITL request resolution

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#35324]
The video covers the issue in detail - https://fathom.video/share/KxykrZeV6LHS1H3J2_pyrP1fEyhyTPYR

I'm adding Mezmo errors as comments below

**Comment by infinitetrooper** [comment]
`Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | executeActivity GetRequestById 66a9470aa8df8237978d952c false [ { id: 89 } ] { 'this.params.id': 89 }
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith WARN rts stdout | 2024-07-31T14:14:47.572Z [WARN] Activity failed {
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   sdkComponent: 'worker',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   taskQueue: 'appsmith-queue',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   isLocal: false,
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   attempt: 1,
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   namespace: 'default',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   taskToken: 'CiQwYmNhYWI0OC0wMmZkLTQ3MDAtOTgyOC1lODg4NzMxMjlmMmESCDcxTUk0MlFLGiRlMmEzMGJmZC00ZjY2LTRiZjUtYTVjMy05Yjk3NDk1NmJkOTUgMCgBMgE4Qg9leGVjdXRlQWN0aXZpdHlKCQgCEKSkwAEYAQ==',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowId: '71MI42QK',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowRunId: 'e2a30bfd-4f66-4bf5-a5c3-9b974956bd95',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowType: 'executeWorkflow',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   activityId: '8',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   activityType: 'executeActivity',
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith error rts stdout |   error: TypeError: Cannot read properties of undefined (reading 'error')
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at /opt/appsmith/rts/bundle/server.js:170:18489
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async executeActivity (/opt/appsmith/rts/bundle/server.js:170:17920)
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async Activity.execute (/opt/appsmith/rts/node_modules/@temporalio/worker/lib/activity.js:62:20)
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async /opt/appsmith/rts/node_modules/@temporalio/worker/lib/activity.js:91:32
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async /opt/appsmith/rts/node_modules/@temporalio/worker/lib/worker.js:636:30,
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   durationMs: 8
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | }
Jul 31 19:44:47 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith debug editor stderr | {"level":"debug","ts":1722435287.7795186,"logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"127.0.0.1:8080","total_upstreams":1}
 (edited) 


Akhil Varma
  [7:53 PM](https://theappsmith.slack.com/archives/D04EFN7CSEA/p1722435831516149)
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | executeActivity GetRequestById 66a9470aa8df8237978d952c false [ { id: 91 } ] { 'this.params.id': 91 }
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith WARN rts stdout | 2024-07-31T14:22:01.970Z [WARN] Activity failed {
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   sdkComponent: 'worker',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   taskQueue: 'appsmith-queue',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   isLocal: false,
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   attempt: 3,
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   namespace: 'default',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   taskToken: 'CiQwYmNhYWI0OC0wMmZkLTQ3MDAtOTgyOC1lODg4NzMxMjlmMmESCEFVRFdHVFk4GiRjMWMwMDJkMC01NzA1LTQzMTAtYWU2YS05YTRiMzQ1ZjljNzggMygDMgE4Qg9leGVjdXRlQWN0aXZpdHlKCQgBEOyZwAEYAQ==',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowId: 'AUDWGTY8',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowRunId: 'c1c002d0-5705-4310-ae6a-9a4b345f9c78',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   workflowType: 'executeWorkflow',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   activityId: '8',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   activityType: 'executeActivity',
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith error rts stdout |   error: TypeError: Cannot read properties of undefined (reading 'error')
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at /opt/appsmith/rts/bundle/server.js:170:18489
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async executeActivity (/opt/appsmith/rts/bundle/server.js:170:17920)
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async Activity.execute (/opt/appsmith/rts/node_modules/@temporalio/worker/lib/activity.js:62:20)
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async /opt/appsmith/rts/node_modules/@temporalio/worker/lib/activity.js:91:32
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |       at async /opt/appsmith/rts/node_modules/@temporalio/worker/lib/worker.js:636:30,
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   durationMs: 8
Jul 31 19:52:01 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | }
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith debug editor stderr | {"level":"debug","ts":1722435722.0874639,"logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"127.0.0.1:8080","total_upstreams":1}
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith backend stdout | [2024-07-31 14:22:02,092] requestId=9e77b6a6-56c1-41b3-a855-9de1ccfddb28 userEmail=tom@appsmith.com traceId= spanId= - Getting activities for Workflow 66a946c6a8df8237978d950c and Run AUDWGTY8
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | Sending analytics event WORKFLOW_FAILED 66a946c6a8df8237978d950c WORKFLOW {
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   runId: 'AUDWGTY8',
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   isTest: false,
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   errorName: 'ActivityFailure',
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |   errorMessage: 'Activity task failed'
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | }
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith Pending Review (Procurement)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout | Workflow resolution string {"workflowId":"66a946c6a8df8237978d950c","requestId":"66aa4855a8df8237978d9c33","resolution":"Approve","runId":"AUDWGTY8"}
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith Error rts stdout | Error parsing result in activityTaskFailed SyntaxError: "undefined" is not valid JSON
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at JSON.parse (<anonymous>)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at transforTaskFailedEvent (/opt/appsmith/rts/bundle/server.js:170:9425)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at transformEvent (/opt/appsmith/rts/bundle/server.js:170:10217)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at /opt/appsmith/rts/bundle/server.js:170:5272
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at Array.reduce (<anonymous>)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at transformHistoryEvents (/opt/appsmith/rts/bundle/server.js:170:5199)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at HistoryService.listWorkflowActivities (/opt/appsmith/rts/bundle/server.js:170:11884)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 31 19:52:02 mariner-appsmith-6cdb4c9f9-zvjr6 appsmith rts stdout |     at async listWorkflowActivities`

**Comment by infinitetrooper** [comment]
![image](https://github.com/user-attachments/assets/fddad198-b496-4602-956f-6f13a6a482e5)

**Comment by nsarupr** [comment]
For now, we were not able to reproduce the issue.
