### ISSUE TITLE
[Bug] Datasource has null plugin id

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4150]
## Description
Sentry issue: https://sentry.io/organizations/appsmith/issues/2362059635/?end=2021-04-26T23%3A29%3A59&project=1546547&query=is%3Aunresolved&start=2021-04-24T00%3A00%3A00&utc=true 

```
java.lang.IllegalArgumentException: The given id must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:198)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.appsmith.server.controllers.ActionController#executeAction(ExecuteActionDTO) [DispatcherHandler]
Stack trace:
		at org.springframework.util.Assert.notNull(Assert.java:198)
		at com.appsmith.server.repositories.BaseRepositoryImpl.findById(BaseRepositoryImpl.java:73)
```

```
at com.appsmith.server.services.PluginServiceImpl.findById(PluginServiceImpl.java:252)
		at com.appsmith.server.services.NewActionServiceImpl.lambda$executeAction$17(NewActionServiceImpl.java:519)
```

**Comment by Nikhil-Nandagopal** [comment]
closing as we haven't seen it in awhile
