### ISSUE TITLE
[Bug]: appsmith-server compile error

### ISSUE THREAD

**Issue by JingyaFeng** [appsmithorg/appsmith#8607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sorry, I can't find any other issue type to report the problem.
I'm compiling app-server. But the appsmith-server project reports compile error.

Error is :
---------------------------------------------------------------------------
[INFO] Compiling 412 source files to D:\mywork\appsmith\app\server\appsmith-server\target\classes
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.2, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$2$1.setOverloadKind(DeferredAttr.java:172)
....

[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] /D:/mywork/appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java: some input file use or overlay decrapted API
[INFO] /D:/mywork/appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java: for detailed information, please use  -Xlint:deprecation 
to recompile.
[INFO] /D:/mywork/appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java:some input file use unchecked or unsafe operation
[INFO] /D:/mywork/appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java: for detailed information, please use -Xlint:unchecked 
to recompile. 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.863 s
[INFO] Finished at: 2021-10-19T13:57:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project server: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project server: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
......
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1224)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
......

[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### Steps To Reproduce

```markdown
compile env:
- JDK version: jdk-11.0.2
- OS: Windows10
- Maven: 3.8.1
```

### Environment

Release

### Version

Self-Hosted

**Comment by JingyaFeng** [comment]
Fixed it with jdk 12. Thank you very much.
