### ISSUE TITLE
[Bug]: Passwords not working after update

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#9724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can no longer authenticate on site after update.

```
backend stdout |  - Empty encoded password
backend stdout |
backend stdout |  - In the login failure handler. Cause: Invalid Credentials
backend stdout | org.springframework.security.authentication.BadCredentialsException: Invalid Credentials
backend stdout |        at org.springframework.security.authentication.AbstractUserDetailsReactiveAuthenticationManager.lambda$authenticate$3(AbstractUserDetailsReactiveAuthenticationManager.java:104)
backend stdout |        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
backend stdout |        at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
backend stdout |        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
backend stdout |        at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:160)
backend stdout |        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:179)
backend stdout |        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
backend stdout |        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
backend stdout |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
backend stdout |        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
backend stdout |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
backend stdout |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
backend stdout |        at java.base/java.lang.Thread.run(Thread.java:829)
backend stdout |
rts stdout | ns:/# socket jeFZMHkD_C8gnEaXAAAK joined the room jeFZMHkD_C8gnEaXAAAK
rts stdout |
rts stdout | Error in socket connected handler TypeError: Cannot read property 'match' of undefined
rts stdout |     at /opt/appsmith/rts/server.js:158:52
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |     at __awaiter (/opt/appsmith/rts/server.js:4:12)
rts stdout |     at tryAuth (/opt/appsmith/rts/server.js:148:12)
rts stdout |     at /opt/appsmith/rts/server.js:128:37
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |
rts stdout | ns:/page/edit# socket JU0JSXUHHFMqobYRAAAL joined the room JU0JSXUHHFMqobYRAAAL
rts stdout |
rts stdout | Error in socket connected handler TypeError: Cannot read property 'match' of undefined
rts stdout |     at /opt/appsmith/rts/server.js:158:52
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |     at __awaiter (/opt/appsmith/rts/server.js:4:12)
rts stdout |     at tryAuth (/opt/appsmith/rts/server.js:148:12)
rts stdout |     at /opt/appsmith/rts/server.js:136:37
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |
rts stdout | ns:/# socket jeFZMHkD_C8gnEaXAAAK left the room jeFZMHkD_C8gnEaXAAAK
rts stdout | ns:/page/edit# socket JU0JSXUHHFMqobYRAAAL left the room JU0JSXUHHFMqobYRAAAL
rts stdout |
rts stdout | ns:/# socket nzjLzEsApTS_vb8YAAAN joined the room nzjLzEsApTS_vb8YAAAN
rts stdout |
rts stdout | Error in socket connected handler TypeError: Cannot read property 'match' of undefined
rts stdout |     at /opt/appsmith/rts/server.js:158:52
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |     at __awaiter (/opt/appsmith/rts/server.js:4:12)
rts stdout |     at tryAuth (/opt/appsmith/rts/server.js:148:12)
rts stdout |     at /opt/appsmith/rts/server.js:128:37
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |
rts stdout | ns:/page/edit# socket kg2bWGIuLaftWlZiAAAO joined the room kg2bWGIuLaftWlZiAAAO
rts stdout |
rts stdout | Error in socket connected handler TypeError: Cannot read property 'match' of undefined
rts stdout |     at /opt/appsmith/rts/server.js:158:52
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |     at __awaiter (/opt/appsmith/rts/server.js:4:12)
rts stdout |     at tryAuth (/opt/appsmith/rts/server.js:148:12)
rts stdout |     at /opt/appsmith/rts/server.js:136:37
rts stdout |     at Generator.next (<anonymous>)
rts stdout |     at /opt/appsmith/rts/server.js:8:71
rts stdout |     at new Promise (<anonymous>)
rts stdout |
rts stdout | ns:/# socket nzjLzEsApTS_vb8YAAAN left the room nzjLzEsApTS_vb8YAAAN
rts stdout | ns:/page/edit# socket kg2bWGIuLaftWlZiAAAO left the room kg2bWGIuLaftWlZiAAAO
rts stdout |
backend stdout |  - Empty encoded password
backend stdout |

```

### Steps To Reproduce

update image to latest release

### Environment

Production

### Version

Self-Hosted

**Comment by japrogramer** [comment]
had to reset my password, but bug is confirmed because password on my local dev machine is simple

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer can you share the steps to reproduce the issue?

**Comment by japrogramer** [comment]
I pulled the latest code from the release branch

than I build the image by doing

```
cd app/server
mvn clean compile
./build.sh -DskipTests
cd ../..
docker buildx build --platform linux/amd64 -t appsmith:latest . -o type=docker
```

than I restarted my container using the new image

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer are you able to reproduce this issue with a new user on your instance?
